/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.infosmart.portal.pojo;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>DWPAS_C_KPI_USER_CNT</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_c_kpi_user_cnt.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DwpasCKpiUserCnt {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private String id;

	/**
	 * This property corresponds to db column <tt>KPI_NAME</tt>.
	 */
	private String kpiName;

	/**
	 * This property corresponds to db column <tt>TAOBAO_KPI_CODE</tt>.
	 */
	private String taobaoKpiCode;

	/**
	 * This property corresponds to db column <tt>ALIPAY_KPI_CODE</tt>.
	 */
	private String alipayKpiCode;

	/**
	 * This property corresponds to db column <tt>OUT_KPI_CODE</tt>.
	 */
	private String outKpiCode;

	/**
	 * This property corresponds to db column <tt>OTHER_KPI_CODE</tt>.
	 */
	private String otherKpiCode;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public String getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(String id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>kpiName</tt>.
     *
     * @return property value of kpiName
     */
	public String getKpiName() {
		return kpiName;
	}
	
	/**
	 * Setter method for property <tt>kpiName</tt>.
	 * 
	 * @param kpiName value to be assigned to property kpiName
     */
	public void setKpiName(String kpiName) {
		this.kpiName = kpiName;
	}

    /**
     * Getter method for property <tt>taobaoKpiCode</tt>.
     *
     * @return property value of taobaoKpiCode
     */
	public String getTaobaoKpiCode() {
		return taobaoKpiCode;
	}
	
	/**
	 * Setter method for property <tt>taobaoKpiCode</tt>.
	 * 
	 * @param taobaoKpiCode value to be assigned to property taobaoKpiCode
     */
	public void setTaobaoKpiCode(String taobaoKpiCode) {
		this.taobaoKpiCode = taobaoKpiCode;
	}

    /**
     * Getter method for property <tt>alipayKpiCode</tt>.
     *
     * @return property value of alipayKpiCode
     */
	public String getAlipayKpiCode() {
		return alipayKpiCode;
	}
	
	/**
	 * Setter method for property <tt>alipayKpiCode</tt>.
	 * 
	 * @param alipayKpiCode value to be assigned to property alipayKpiCode
     */
	public void setAlipayKpiCode(String alipayKpiCode) {
		this.alipayKpiCode = alipayKpiCode;
	}

    /**
     * Getter method for property <tt>outKpiCode</tt>.
     *
     * @return property value of outKpiCode
     */
	public String getOutKpiCode() {
		return outKpiCode;
	}
	
	/**
	 * Setter method for property <tt>outKpiCode</tt>.
	 * 
	 * @param outKpiCode value to be assigned to property outKpiCode
     */
	public void setOutKpiCode(String outKpiCode) {
		this.outKpiCode = outKpiCode;
	}

    /**
     * Getter method for property <tt>otherKpiCode</tt>.
     *
     * @return property value of otherKpiCode
     */
	public String getOtherKpiCode() {
		return otherKpiCode;
	}
	
	/**
	 * Setter method for property <tt>otherKpiCode</tt>.
	 * 
	 * @param otherKpiCode value to be assigned to property otherKpiCode
     */
	public void setOtherKpiCode(String otherKpiCode) {
		this.otherKpiCode = otherKpiCode;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
