package com.infosmart.portal.pojo;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.log4j.Logger;

import com.infosmart.portal.util.DateUtils;
import com.infosmart.portal.util.MathUtils;

/**
 * 指标数据
 * 
 * @author infosmart
 * 
 */
public class DwpasStKpiData {
	private final Logger logger = Logger.getLogger(this.getClass());
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_kpi_data.KPI_ID
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	private Long kpiId;

	/**
	 * 指标编码
	 */
	private String kpiCode;

	/**
	 * 指标名字
	 */
	private String kpiName;
	/**
	 * 指标信息
	 */
	private DwpasCKpiInfo dwpasCKpiInfo;

	/**
	 * 数据时间
	 */
	private String reportDate;

	/**
	 * 基础�?
	 */
	private BigDecimal baseValue = new BigDecimal(0);

	/**
	 * 基础显示
	 */
	private BigDecimal baseValueShow;

	/**
	 * 显示�?
	 */
	private BigDecimal showValue = new BigDecimal(0);

	// 格式化显示
	private String showValueDesc;

	/**
	 * 均�??
	 */
	private BigDecimal ageValue;

	/** 平均值显示 */
	private BigDecimal averageShow;

	/**
	 * 趋势�?
	 */
	private BigDecimal trendValue;

	/**
	 * 占比�?
	 */
	private BigDecimal perValue;

	/**
	 * �?大�??
	 */
	private BigDecimal maxValue;

	/** 最大显示值 */
	private BigDecimal maxShow;

	/**
	 * �?小�??
	 */
	private BigDecimal minValue;

	/** 最小显示值 */
	private BigDecimal minShow;

	/**
	 * 保留字段1
	 */
	private BigDecimal value1;

	/**
	 * 保留字段2
	 */
	private BigDecimal value2;

	/**
	 * 保留字段3
	 */
	private BigDecimal value3;

	/**
	 * 排名
	 */
	private Short sortCnt;

	/**
	 * 日期类型
	 */
	private String dateType;

	/**
	 * 单位
	 */
	private String unit;

	/**
	 * 日统计指�?
	 */
	public static final String DATE_TYPE_OF_DAY = "D";
	/**
	 * 周统计指�?
	 */
	public static final String DATE_TYPE_OF_WEEK = "W";
	/**
	 * 月统计指�?
	 */
	public static final String DATE_TYPE_OF_MONTH = "M";

	/**
	 * 值产生的时间
	 */
	private String gmtMaxTime;
	// yyyy-MM-dd
	private String gmtMaxTimeDesc;
	// 星期
	private String gmtMaxTimeWeekly;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_kpi_data.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_kpi_data.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	private Date gmtModified;

	public DwpasStKpiData() {
	}

	public DwpasStKpiData(DwpasCKpiInfo dwpasCKpiInfo, String reportDate,
			BigDecimal baseValue) {
		super();
		this.dwpasCKpiInfo = dwpasCKpiInfo;
		this.reportDate = reportDate;
		this.baseValue = baseValue;
	}

	public String getGmtMaxTimeDesc() {
		if (this.gmtMaxTime != null) {
			// this.logger.info("转化为日期..............................");
			java.util.Date gmtMaxTimeD = DateUtils.parseByFormatRule(
					this.gmtMaxTime, "yyyyMMdd");
			gmtMaxTimeDesc = DateUtils.formatByFormatRule(gmtMaxTimeD,
					"yyyy-MM-dd");
		}
		return gmtMaxTimeDesc;
	}

	public String getGmtMaxTimeWeekly() {
		if (this.gmtMaxTime != null) {
			// this.logger.info("转化为星期..............................");
			java.util.Date gmtMaxTimeD = DateUtils.parseByFormatRule(
					this.gmtMaxTime, "yyyyMMdd");
			if (gmtMaxTimeD != null) {
				gmtMaxTimeWeekly = DateUtils.getDayWeek(new java.sql.Date(
						gmtMaxTimeD.getTime()));
			}
			return gmtMaxTimeWeekly;
		} else {
			return null;
		}
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.KPI_ID
	 * 
	 * @return the value of dwpas_st_kpi_data.KPI_ID
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public Long getKpiId() {
		return kpiId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.KPI_ID
	 * 
	 * @param kpiId
	 *            the value for dwpas_st_kpi_data.KPI_ID
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setKpiId(Long kpiId) {
		this.kpiId = kpiId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.KPI_CODE
	 * 
	 * @return the value of dwpas_st_kpi_data.KPI_CODE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public String getKpiCode() {
		return kpiCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.KPI_CODE
	 * 
	 * @param kpiCode
	 *            the value for dwpas_st_kpi_data.KPI_CODE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setKpiCode(String kpiCode) {
		this.kpiCode = kpiCode == null ? null : kpiCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.REPORT_DATE
	 * 
	 * @return the value of dwpas_st_kpi_data.REPORT_DATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public String getReportDate() {
		return reportDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.REPORT_DATE
	 * 
	 * @param reportDate
	 *            the value for dwpas_st_kpi_data.REPORT_DATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setReportDate(String reportDate) {
		this.reportDate = reportDate == null ? null : reportDate.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.BASE_VALUE
	 * 
	 * @return the value of dwpas_st_kpi_data.BASE_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getBaseValue() {
		return baseValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.BASE_VALUE
	 * 
	 * @param baseValue
	 *            the value for dwpas_st_kpi_data.BASE_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setBaseValue(BigDecimal baseValue) {
		this.baseValue = baseValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.AGE_VALUE
	 * 
	 * @return the value of dwpas_st_kpi_data.AGE_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getAgeValue() {
		return ageValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.AGE_VALUE
	 * 
	 * @param ageValue
	 *            the value for dwpas_st_kpi_data.AGE_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setAgeValue(BigDecimal ageValue) {
		this.ageValue = ageValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.TREND_VALUE
	 * 
	 * @return the value of dwpas_st_kpi_data.TREND_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getTrendValue() {
		return trendValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.TREND_VALUE
	 * 
	 * @param trendValue
	 *            the value for dwpas_st_kpi_data.TREND_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setTrendValue(BigDecimal trendValue) {
		this.trendValue = trendValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.PER_VALUE
	 * 
	 * @return the value of dwpas_st_kpi_data.PER_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getPerValue() {
		return perValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.PER_VALUE
	 * 
	 * @param perValue
	 *            the value for dwpas_st_kpi_data.PER_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setPerValue(BigDecimal perValue) {
		this.perValue = perValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.MAX_VALUE
	 * 
	 * @return the value of dwpas_st_kpi_data.MAX_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getMaxValue() {
		return maxValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.MAX_VALUE
	 * 
	 * @param maxValue
	 *            the value for dwpas_st_kpi_data.MAX_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setMaxValue(BigDecimal maxValue) {
		this.maxValue = maxValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.MIN_VALUE
	 * 
	 * @return the value of dwpas_st_kpi_data.MIN_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getMinValue() {
		return minValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.MIN_VALUE
	 * 
	 * @param minValue
	 *            the value for dwpas_st_kpi_data.MIN_VALUE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setMinValue(BigDecimal minValue) {
		this.minValue = minValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.VALUE1
	 * 
	 * @return the value of dwpas_st_kpi_data.VALUE1
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getValue1() {
		return value1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.VALUE1
	 * 
	 * @param value1
	 *            the value for dwpas_st_kpi_data.VALUE1
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setValue1(BigDecimal value1) {
		this.value1 = value1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.VALUE2
	 * 
	 * @return the value of dwpas_st_kpi_data.VALUE2
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getValue2() {
		return value2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.VALUE2
	 * 
	 * @param value2
	 *            the value for dwpas_st_kpi_data.VALUE2
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setValue2(BigDecimal value2) {
		this.value2 = value2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.VALUE3
	 * 
	 * @return the value of dwpas_st_kpi_data.VALUE3
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public BigDecimal getValue3() {
		return value3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.VALUE3
	 * 
	 * @param value3
	 *            the value for dwpas_st_kpi_data.VALUE3
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setValue3(BigDecimal value3) {
		this.value3 = value3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.SORT_CNT
	 * 
	 * @return the value of dwpas_st_kpi_data.SORT_CNT
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public Short getSortCnt() {
		if (sortCnt == null || sortCnt <= 0)
			sortCnt = 0;
		return sortCnt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.SORT_CNT
	 * 
	 * @param sortCnt
	 *            the value for dwpas_st_kpi_data.SORT_CNT
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setSortCnt(Short sortCnt) {
		this.sortCnt = sortCnt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.DATE_TYPE
	 * 
	 * @return the value of dwpas_st_kpi_data.DATE_TYPE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public String getDateType() {
		return dateType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.DATE_TYPE
	 * 
	 * @param dateType
	 *            the value for dwpas_st_kpi_data.DATE_TYPE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setDateType(String dateType) {
		this.dateType = dateType == null ? null : dateType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.GMT_MAX_TIME
	 * 
	 * @return the value of dwpas_st_kpi_data.GMT_MAX_TIME
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public String getGmtMaxTime() {
		return gmtMaxTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.GMT_MAX_TIME
	 * 
	 * @param gmtMaxTime
	 *            the value for dwpas_st_kpi_data.GMT_MAX_TIME
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setGmtMaxTime(String gmtMaxTime) {
		this.gmtMaxTime = gmtMaxTime == null ? null : gmtMaxTime.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.GMT_CREATE
	 * 
	 * @return the value of dwpas_st_kpi_data.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.GMT_CREATE
	 * 
	 * @param gmtCreate
	 *            the value for dwpas_st_kpi_data.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_kpi_data.GMT_MODIFIED
	 * 
	 * @return the value of dwpas_st_kpi_data.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_kpi_data.GMT_MODIFIED
	 * 
	 * @param gmtModified
	 *            the value for dwpas_st_kpi_data.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:55:25 CST 2012
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public DwpasCKpiInfo getDwpasCKpiInfo() {
		return dwpasCKpiInfo;
	}

	public void setDwpasCKpiInfo(DwpasCKpiInfo dwpasCKpiInfo) {
		this.dwpasCKpiInfo = dwpasCKpiInfo;
	}

	public String getShowValueDesc() {
		if (this.dwpasCKpiInfo == null) {
			this.logger.info("没有指标信息");
			this.showValue = this.baseValue;
		} else if (this.getBaseValue() != null) {
			// 计算�?
			BigDecimal calUnit = new BigDecimal(Math.pow(10,
					this.dwpasCKpiInfo.getConvertNum()));
			if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_DIVIDE).equals(
					this.dwpasCKpiInfo.getConvertType())) {
				// 除法
				showValue = this.getBaseValue()
						.divide(calUnit, dwpasCKpiInfo.getDecimalNum(),
								BigDecimal.ROUND_HALF_UP);
			} else if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_MULTIPLY)
					.equals(this.dwpasCKpiInfo.getConvertType())) {
				// 乘法
				showValue = this.getBaseValue().multiply(calUnit);
			} else {
				showValue = this.getBaseValue();
			}
		}
		// 格式化数
		if (this.dwpasCKpiInfo != null) {
			showValueDesc = MathUtils.round(showValue,
					dwpasCKpiInfo.getDecimalNum()).toString();
		}
		return showValueDesc;
	}

	public BigDecimal getShowValue() {
		if (this.showValue != null) {
			if (this.dwpasCKpiInfo == null) {
				this.logger.info("没有指标信息");
				this.showValue = this.baseValue;
			} else if (this.getBaseValue() != null) {
				// 计算�?
				if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_DIVIDE).equals(
						this.dwpasCKpiInfo.getConvertType())) {
					// 除法
					showValue = this.getBaseValue().divide(
							new BigDecimal(Math.pow(10,
									this.dwpasCKpiInfo.getConvertNum())),
							dwpasCKpiInfo.getDecimalNum(),
							BigDecimal.ROUND_HALF_UP);
				} else if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_MULTIPLY)
						.equals(this.dwpasCKpiInfo.getConvertType())) {
					// 乘法
					showValue = this.getBaseValue().multiply(
							new BigDecimal(Math.pow(10,
									this.dwpasCKpiInfo.getConvertNum())));
				} else {
					showValue = this.getBaseValue();
				}
			}
			// 按规则转换数据格式
			if (this.dwpasCKpiInfo != null
					&& dwpasCKpiInfo.getDecimalNum() != null
					&& dwpasCKpiInfo.getDecimalNum() != 0) {
				showValue = MathUtils.round(showValue,
						dwpasCKpiInfo.getDecimalNum());
			}
			return showValue;
		} else {
			return null;
		}
	}

	public String getKpiName() {
		return kpiName;
	}

	public void setKpiName(String kpiName) {
		this.kpiName = kpiName;
	}

	public void setShowValue(BigDecimal showValue) {
		this.showValue = showValue;
	}

	public BigDecimal getAverageShow() {
		if (this.ageValue != null) {
			if (this.dwpasCKpiInfo == null) {
				this.logger.info("没有指标信息");
				this.averageShow = this.ageValue;
			} else if (this.getBaseValue() != null) {
				// 计算�?
				BigDecimal calUnit = new BigDecimal(Math.pow(10,
						this.dwpasCKpiInfo.getConvertNum()));
				if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_DIVIDE).equals(
						this.dwpasCKpiInfo.getConvertType())) {
					// 除法
					averageShow = this.ageValue.divide(calUnit,
							dwpasCKpiInfo.getDecimalNum(),
							BigDecimal.ROUND_HALF_UP);
				} else if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_MULTIPLY)
						.equals(this.dwpasCKpiInfo.getConvertType())) {
					// 乘法
					averageShow = ageValue.multiply(calUnit);
				} else {
					averageShow = ageValue;
				}
			}
			// 格式化数据
			if (this.dwpasCKpiInfo != null) {
				if (dwpasCKpiInfo.getDecimalNum() != 0) {
					averageShow = MathUtils.round(averageShow,
							dwpasCKpiInfo.getDecimalNum());
				}
			}
			return averageShow;
		} else {
			return null;
		}
	}

	public void setAverageShow(BigDecimal averageShow) {
		this.averageShow = averageShow;
	}

	public BigDecimal getMaxShow() {
		if (this.maxValue != null) {
			if (this.dwpasCKpiInfo == null) {
				this.logger.info("没有指标信息");
				this.maxShow = this.maxValue;
			} else if (this.getBaseValue() != null) {
				// 计算??
				BigDecimal calUnit = new BigDecimal(Math.pow(10,
						this.dwpasCKpiInfo.getConvertNum()));
				if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_DIVIDE).equals(
						this.dwpasCKpiInfo.getConvertType())) {
					// 除法
					maxShow = this.maxValue.divide(calUnit,
							dwpasCKpiInfo.getDecimalNum(),
							BigDecimal.ROUND_HALF_UP);
				} else if (String.valueOf(DwpasCKpiInfo.CONVERT_TYPE_MULTIPLY)
						.equals(this.dwpasCKpiInfo.getConvertType())) {
					// 乘法
					maxShow = maxValue.multiply(calUnit);
				} else {
					maxShow = maxValue;
				}
			}
			// 格式化数据
			if (this.dwpasCKpiInfo != null) {
				if (dwpasCKpiInfo.getDecimalNum() != 0) {
					maxShow = MathUtils.round(maxShow,
							dwpasCKpiInfo.getDecimalNum());
				}
			}
			return maxShow;
		} else {
			return null;
		}
	}

	public void setMaxShow(BigDecimal maxShow) {
		this.maxShow = maxShow;
	}

	public BigDecimal getBaseValueShow() {
		return baseValueShow;
	}

	public void setBaseValueShow(BigDecimal baseValueShow) {
		this.baseValueShow = baseValueShow;
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public BigDecimal getMinShow() {
		return minShow;
	}

	public void setMinShow(BigDecimal minShow) {
		this.minShow = minShow;
	}

}