/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.infosmart.portal.pojo;

// auto generated imports
import java.util.Date;
import java.math.BigDecimal;

/**
 * A data object class directly models database table <tt>DWPAS_C_HELPRATE_SHOW</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_c_helprate_show.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DwpasCHelprateShow {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>PRODUCT_ID</tt>.
	 */
	private String productId;

	/**
	 * This property corresponds to db column <tt>PRE_ALERT_VALUE</tt>.
	 */
	private BigDecimal preAlertValue;

	/**
	 * This property corresponds to db column <tt>ALERT_VALUE</tt>.
	 */
	private BigDecimal alertValue;

	/**
	 * This property corresponds to db column <tt>MAX_VALUE</tt>.
	 */
	private BigDecimal maxValue;

	/**
	 * This property corresponds to db column <tt>MIN_VALUE</tt>.
	 */
	private BigDecimal minValue;

	/**
	 * This property corresponds to db column <tt>SHOW_ORDER</tt>.
	 */
	private int showOrder;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>productId</tt>.
     *
     * @return property value of productId
     */
	public String getProductId() {
		return productId;
	}
	
	/**
	 * Setter method for property <tt>productId</tt>.
	 * 
	 * @param productId value to be assigned to property productId
     */
	public void setProductId(String productId) {
		this.productId = productId;
	}

    /**
     * Getter method for property <tt>preAlertValue</tt>.
     *
     * @return property value of preAlertValue
     */
	public BigDecimal getPreAlertValue() {
		return preAlertValue;
	}
	
	/**
	 * Setter method for property <tt>preAlertValue</tt>.
	 * 
	 * @param preAlertValue value to be assigned to property preAlertValue
     */
	public void setPreAlertValue(BigDecimal preAlertValue) {
		this.preAlertValue = preAlertValue;
	}

    /**
     * Getter method for property <tt>alertValue</tt>.
     *
     * @return property value of alertValue
     */
	public BigDecimal getAlertValue() {
		return alertValue;
	}
	
	/**
	 * Setter method for property <tt>alertValue</tt>.
	 * 
	 * @param alertValue value to be assigned to property alertValue
     */
	public void setAlertValue(BigDecimal alertValue) {
		this.alertValue = alertValue;
	}

    /**
     * Getter method for property <tt>maxValue</tt>.
     *
     * @return property value of maxValue
     */
	public BigDecimal getMaxValue() {
		return maxValue;
	}
	
	/**
	 * Setter method for property <tt>maxValue</tt>.
	 * 
	 * @param maxValue value to be assigned to property maxValue
     */
	public void setMaxValue(BigDecimal maxValue) {
		this.maxValue = maxValue;
	}

    /**
     * Getter method for property <tt>minValue</tt>.
     *
     * @return property value of minValue
     */
	public BigDecimal getMinValue() {
		return minValue;
	}
	
	/**
	 * Setter method for property <tt>minValue</tt>.
	 * 
	 * @param minValue value to be assigned to property minValue
     */
	public void setMinValue(BigDecimal minValue) {
		this.minValue = minValue;
	}

    /**
     * Getter method for property <tt>showOrder</tt>.
     *
     * @return property value of showOrder
     */
	public int getShowOrder() {
		return showOrder;
	}
	
	/**
	 * Setter method for property <tt>showOrder</tt>.
	 * 
	 * @param showOrder value to be assigned to property showOrder
     */
	public void setShowOrder(int showOrder) {
		this.showOrder = showOrder;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
