package com.infosmart.portal.pojo;


import java.util.Date;

/**
 * A data object class directly models database table <tt>DWPAS_ST_DROGUE_DATA</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_st_drogue_data.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DwpasStDrogueData {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>REPORT_DATE</tt>.
	 */
	private String reportDate;

	/**
	 * This property corresponds to db column <tt>CAT_ID</tt>.
	 */
	private String catId;

	/**
	 * This property corresponds to db column <tt>GGRAND_TITLE</tt>.
	 */
	private String ggrandTitle;

	/**
	 * This property corresponds to db column <tt>GRAND_TITLE</tt>.
	 */
	private String grandTitle;

	/**
	 * This property corresponds to db column <tt>FATHER_TITLE</tt>.
	 */
	private String fatherTitle;

	/**
	 * This property corresponds to db column <tt>CAT_TITLE</tt>.
	 */
	private String catTitle;

	/**
	 * This property corresponds to db column <tt>ALL_TITLE</tt>.
	 */
	private String allTitle;

	/**
	 * This property corresponds to db column <tt>CNT</tt>.
	 */
	private long cnt;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>reportDate</tt>.
     *
     * @return property value of reportDate
     */
	public String getReportDate() {
		return reportDate;
	}
	
	/**
	 * Setter method for property <tt>reportDate</tt>.
	 * 
	 * @param reportDate value to be assigned to property reportDate
     */
	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

    /**
     * Getter method for property <tt>catId</tt>.
     *
     * @return property value of catId
     */
	public String getCatId() {
		return catId;
	}
	
	/**
	 * Setter method for property <tt>catId</tt>.
	 * 
	 * @param catId value to be assigned to property catId
     */
	public void setCatId(String catId) {
		this.catId = catId;
	}

    /**
     * Getter method for property <tt>ggrandTitle</tt>.
     *
     * @return property value of ggrandTitle
     */
	public String getGgrandTitle() {
		return ggrandTitle;
	}
	
	/**
	 * Setter method for property <tt>ggrandTitle</tt>.
	 * 
	 * @param ggrandTitle value to be assigned to property ggrandTitle
     */
	public void setGgrandTitle(String ggrandTitle) {
		this.ggrandTitle = ggrandTitle;
	}

    /**
     * Getter method for property <tt>grandTitle</tt>.
     *
     * @return property value of grandTitle
     */
	public String getGrandTitle() {
		return grandTitle;
	}
	
	/**
	 * Setter method for property <tt>grandTitle</tt>.
	 * 
	 * @param grandTitle value to be assigned to property grandTitle
     */
	public void setGrandTitle(String grandTitle) {
		this.grandTitle = grandTitle;
	}

    /**
     * Getter method for property <tt>fatherTitle</tt>.
     *
     * @return property value of fatherTitle
     */
	public String getFatherTitle() {
		return fatherTitle;
	}
	
	/**
	 * Setter method for property <tt>fatherTitle</tt>.
	 * 
	 * @param fatherTitle value to be assigned to property fatherTitle
     */
	public void setFatherTitle(String fatherTitle) {
		this.fatherTitle = fatherTitle;
	}

    /**
     * Getter method for property <tt>catTitle</tt>.
     *
     * @return property value of catTitle
     */
	public String getCatTitle() {
		return catTitle;
	}
	
	/**
	 * Setter method for property <tt>catTitle</tt>.
	 * 
	 * @param catTitle value to be assigned to property catTitle
     */
	public void setCatTitle(String catTitle) {
		this.catTitle = catTitle;
	}

    /**
     * Getter method for property <tt>allTitle</tt>.
     *
     * @return property value of allTitle
     */
	public String getAllTitle() {
		return allTitle;
	}
	
	/**
	 * Setter method for property <tt>allTitle</tt>.
	 * 
	 * @param allTitle value to be assigned to property allTitle
     */
	public void setAllTitle(String allTitle) {
		this.allTitle = allTitle;
	}

    /**
     * Getter method for property <tt>cnt</tt>.
     *
     * @return property value of cnt
     */
	public long getCnt() {
		return cnt;
	}
	
	/**
	 * Setter method for property <tt>cnt</tt>.
	 * 
	 * @param cnt value to be assigned to property cnt
     */
	public void setCnt(long cnt) {
		this.cnt = cnt;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
