/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.infosmart.portal.pojo;

// auto generated imports
import java.util.Date;
import java.math.BigDecimal;

/**
 * A data object class directly models database table <tt>DWPAS_ST_PLATFORM_DATA</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_st_platform_data.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class DwpasStPlatformData {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>ID</tt>.
	 */
	private String id;

	/**
	 * This property corresponds to db column <tt>REPORT_DATE</tt>.
	 */
	private String reportDate;

	/**
	 * This property corresponds to db column <tt>TAOBAO_RATE</tt>.
	 */
	private BigDecimal taobaoRate;

	/**
	 * This property corresponds to db column <tt>TAOBAO_RATE_TREND</tt>.
	 */
	private BigDecimal taobaoRateTrend;

	/**
	 * This property corresponds to db column <tt>OUT_RATE</tt>.
	 */
	private BigDecimal outRate;

	/**
	 * This property corresponds to db column <tt>OUT_RATE_TREND</tt>.
	 */
	private BigDecimal outRateTrend;

	/**
	 * This property corresponds to db column <tt>INNER_RATE</tt>.
	 */
	private BigDecimal innerRate;

	/**
	 * This property corresponds to db column <tt>INNER_RATE_TREND</tt>.
	 */
	private BigDecimal innerRateTrend;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public String getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(String id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>reportDate</tt>.
     *
     * @return property value of reportDate
     */
	public String getReportDate() {
		return reportDate;
	}
	
	/**
	 * Setter method for property <tt>reportDate</tt>.
	 * 
	 * @param reportDate value to be assigned to property reportDate
     */
	public void setReportDate(String reportDate) {
		this.reportDate = reportDate;
	}

    /**
     * Getter method for property <tt>taobaoRate</tt>.
     *
     * @return property value of taobaoRate
     */
	public BigDecimal getTaobaoRate() {
		return taobaoRate;
	}
	
	/**
	 * Setter method for property <tt>taobaoRate</tt>.
	 * 
	 * @param taobaoRate value to be assigned to property taobaoRate
     */
	public void setTaobaoRate(BigDecimal taobaoRate) {
		this.taobaoRate = taobaoRate;
	}

    /**
     * Getter method for property <tt>taobaoRateTrend</tt>.
     *
     * @return property value of taobaoRateTrend
     */
	public BigDecimal getTaobaoRateTrend() {
		return taobaoRateTrend;
	}
	
	/**
	 * Setter method for property <tt>taobaoRateTrend</tt>.
	 * 
	 * @param taobaoRateTrend value to be assigned to property taobaoRateTrend
     */
	public void setTaobaoRateTrend(BigDecimal taobaoRateTrend) {
		this.taobaoRateTrend = taobaoRateTrend;
	}

    /**
     * Getter method for property <tt>outRate</tt>.
     *
     * @return property value of outRate
     */
	public BigDecimal getOutRate() {
		return outRate;
	}
	
	/**
	 * Setter method for property <tt>outRate</tt>.
	 * 
	 * @param outRate value to be assigned to property outRate
     */
	public void setOutRate(BigDecimal outRate) {
		this.outRate = outRate;
	}

    /**
     * Getter method for property <tt>outRateTrend</tt>.
     *
     * @return property value of outRateTrend
     */
	public BigDecimal getOutRateTrend() {
		return outRateTrend;
	}
	
	/**
	 * Setter method for property <tt>outRateTrend</tt>.
	 * 
	 * @param outRateTrend value to be assigned to property outRateTrend
     */
	public void setOutRateTrend(BigDecimal outRateTrend) {
		this.outRateTrend = outRateTrend;
	}

    /**
     * Getter method for property <tt>innerRate</tt>.
     *
     * @return property value of innerRate
     */
	public BigDecimal getInnerRate() {
		return innerRate;
	}
	
	/**
	 * Setter method for property <tt>innerRate</tt>.
	 * 
	 * @param innerRate value to be assigned to property innerRate
     */
	public void setInnerRate(BigDecimal innerRate) {
		this.innerRate = innerRate;
	}

    /**
     * Getter method for property <tt>innerRateTrend</tt>.
     *
     * @return property value of innerRateTrend
     */
	public BigDecimal getInnerRateTrend() {
		return innerRateTrend;
	}
	
	/**
	 * Setter method for property <tt>innerRateTrend</tt>.
	 * 
	 * @param innerRateTrend value to be assigned to property innerRateTrend
     */
	public void setInnerRateTrend(BigDecimal innerRateTrend) {
		this.innerRateTrend = innerRateTrend;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
