package com.infosmart.portal.pojo;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 产品特征数据
 * 
 * @author infosmart
 * 
 */
public class DwpasStUserFeatureDs {
	private Long ranking;// 排名
	private String ufPercent;// 占百分比
	/**
	 * 占的百分比值
	 */
	private double userPercent = 0.00d;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.product_id
	 * 
	 * 产品ID
	 */
	private String productId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.report_date
	 * 
	 * 统计时间
	 */
	private String reportDate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.feature_type
	 * 
	 * 特征类型(参见产品特征信息 特征类型)
	 */
	private String featureType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.feature_id
	 * 
	 * 特征编码
	 */
	private String featureId;

	private String featureCode;

	/**
	 * 这个值不要保存在数据库
	 */
	private String featureName;

	// 产品特征信息(通过产品ID,特征类型,特征编码三个因素关联)
	private DwpasCUserFeature dwpasCUserFeature;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.user_cnt
	 * 
	 * 使用次数
	 */
	private Long userCnt;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.user_rate
	 * 
	 * 用户数占比
	 */
	private BigDecimal userRate;
	private String areaMapColor = "#C8C8FF";

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_st_user_feature_ds.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	private Date gmtModified;
	private double salesVolume;// 销量

	public String getFeatureCode() {
		return featureCode;
	}

	public void setFeatureCode(String featureCode) {
		this.featureCode = featureCode;
	}

	public String getAreaMapColor() {
		return areaMapColor;
	}

	public void setAreaMapColor(String areaMapColor) {
		this.areaMapColor = areaMapColor;
	}

	public double getUserPercent() {
		try {
			userPercent = Double.parseDouble(this.ufPercent.replace("%", "")) / 100;
		} catch (Exception e) {
			userPercent = 0.00d;
		}
		return userPercent;
	}

	public double getSalesVolume() {
		return salesVolume;
	}

	public void setSalesVolume(double salesVolume) {
		this.salesVolume = salesVolume;
	}

	public void setUserPercent(double userPercent) {
		this.userPercent = userPercent;
	}

	public String getUfPercent() {
		return ufPercent;
	}

	public void setUfPercent(String ufPercent) {
		this.ufPercent = ufPercent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.product_id
	 * 
	 * @return the value of dwpas_st_user_feature_ds.product_id
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.product_id
	 * 
	 * @param productId
	 *            the value for dwpas_st_user_feature_ds.product_id
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setProductId(String productId) {
		this.productId = productId == null ? null : productId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.report_date
	 * 
	 * @return the value of dwpas_st_user_feature_ds.report_date
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public String getReportDate() {
		return reportDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.report_date
	 * 
	 * @param reportDate
	 *            the value for dwpas_st_user_feature_ds.report_date
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setReportDate(String reportDate) {
		this.reportDate = reportDate == null ? null : reportDate.trim();
	}

	public Long getRanking() {
		return ranking;
	}

	public void setRanking(Long ranking) {
		this.ranking = ranking;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.feature_type
	 * 
	 * @return the value of dwpas_st_user_feature_ds.feature_type
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public String getFeatureType() {
		return featureType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.feature_type
	 * 
	 * @param featureType
	 *            the value for dwpas_st_user_feature_ds.feature_type
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setFeatureType(String featureType) {
		this.featureType = featureType == null ? null : featureType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.feature_id
	 * 
	 * @return the value of dwpas_st_user_feature_ds.feature_id
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public String getFeatureId() {
		return featureId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.feature_id
	 * 
	 * @param featureId
	 *            the value for dwpas_st_user_feature_ds.feature_id
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setFeatureId(String featureId) {
		this.featureId = featureId == null ? null : featureId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.user_cnt
	 * 
	 * @return the value of dwpas_st_user_feature_ds.user_cnt
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public Long getUserCnt() {
		return userCnt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.user_cnt
	 * 
	 * @param userCnt
	 *            the value for dwpas_st_user_feature_ds.user_cnt
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setUserCnt(Long userCnt) {
		this.userCnt = userCnt;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.user_rate
	 * 
	 * @return the value of dwpas_st_user_feature_ds.user_rate
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public BigDecimal getUserRate() {
		return userRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.user_rate
	 * 
	 * @param userRate
	 *            the value for dwpas_st_user_feature_ds.user_rate
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setUserRate(BigDecimal userRate) {
		this.userRate = userRate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.GMT_CREATE
	 * 
	 * @return the value of dwpas_st_user_feature_ds.GMT_CREATE
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.GMT_CREATE
	 * 
	 * @param gmtCreate
	 *            the value for dwpas_st_user_feature_ds.GMT_CREATE
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_st_user_feature_ds.GMT_MODIFIED
	 * 
	 * @return the value of dwpas_st_user_feature_ds.GMT_MODIFIED
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_st_user_feature_ds.GMT_MODIFIED
	 * 
	 * @param gmtModified
	 *            the value for dwpas_st_user_feature_ds.GMT_MODIFIED
	 * @ibatorgenerated Tue Feb 28 10:40:40 CST 2012
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public DwpasCUserFeature getDwpasCUserFeature() {
		return dwpasCUserFeature;
	}

	public void setDwpasCUserFeature(DwpasCUserFeature dwpasCUserFeature) {
		this.dwpasCUserFeature = dwpasCUserFeature;
	}

	public String getFeatureName() {
		return featureName;
	}

	public void setFeatureName(String featureName) {
		this.featureName = featureName;
	}
}
