package com.infosmart.portal.pojo;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 产品健康度六维度配置表，�?个产品对应一条配置信息�??
 * 
 * @author infosmart
 * 
 */
public class DwpasCPrdDim {
	/**
	 * 产品ID
	 */
	private String productId;

	/**
	 * 维度�?指标code
	 */
	private String dim1Code;

	/**
	 * 显示的名�?
	 */
	private String dim1Name;

	/**
	 * 维度�?内层�?
	 */
	private BigDecimal dim1InValue;

	/**
	 * 维度�?外层�?
	 */
	private BigDecimal dim1OutValue;

	/**
	 * 维度�?值单�?
	 */
	private String dim1ValueUnit;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim2_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private String dim2Code;

	/**
	 * 显示的名�?
	 */
	private String dim2Name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim2_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim2InValue;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim2_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim2OutValue;

	private String dim2ValueUnit;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim3_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private String dim3Code;

	private String dim3Name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim3_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim3InValue;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim3_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim3OutValue;

	private String dim3ValueUnit;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim4_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private String dim4Code;

	private String dim4Name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim4_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim4InValue;

	private String dim4ValueUnit;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim4_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim4OutValue;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim5_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private String dim5Code;

	private String dim5Name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim5_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim5InValue;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim5_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim5OutValue;

	private String dim5ValueUnit;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim6_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private String dim6Code;
	private String dim6Name;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim6_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim6InValue;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.dim6_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private BigDecimal dim6OutValue;

	private String dim6ValueUnit;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_prd_dim.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	private Date gmtModified;
	
	private String dim1Url;
	private String dim2Url;
	private String dim3Url;
	private String dim4Url;
	private String dim5Url;
	private String dim6Url;

	public String getDim1Url() {
		return dim1Url;
	}

	public void setDim1Url(String dim1Url) {
		this.dim1Url = dim1Url;
	}

	public String getDim2Url() {
		return dim2Url;
	}

	public void setDim2Url(String dim2Url) {
		this.dim2Url = dim2Url;
	}

	public String getDim3Url() {
		return dim3Url;
	}

	public void setDim3Url(String dim3Url) {
		this.dim3Url = dim3Url;
	}

	public String getDim4Url() {
		return dim4Url;
	}

	public void setDim4Url(String dim4Url) {
		this.dim4Url = dim4Url;
	}

	public String getDim5Url() {
		return dim5Url;
	}

	public void setDim5Url(String dim5Url) {
		this.dim5Url = dim5Url;
	}

	public String getDim6Url() {
		return dim6Url;
	}

	public void setDim6Url(String dim6Url) {
		this.dim6Url = dim6Url;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.product_id
	 * 
	 * @return the value of dwpas_c_prd_dim.product_id
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.product_id
	 * 
	 * @param productId
	 *            the value for dwpas_c_prd_dim.product_id
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setProductId(String productId) {
		this.productId = productId == null ? null : productId.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim1_code
	 * 
	 * @return the value of dwpas_c_prd_dim.dim1_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getDim1Code() {
		return dim1Code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim1_code
	 * 
	 * @param dim1Code
	 *            the value for dwpas_c_prd_dim.dim1_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim1Code(String dim1Code) {
		this.dim1Code = dim1Code == null ? null : dim1Code.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim1_in_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim1_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim1InValue() {
		return dim1InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim1_in_value
	 * 
	 * @param dim1InValue
	 *            the value for dwpas_c_prd_dim.dim1_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim1InValue(BigDecimal dim1InValue) {
		this.dim1InValue = dim1InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim1_out_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim1_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim1OutValue() {
		return dim1OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim1_out_value
	 * 
	 * @param dim1OutValue
	 *            the value for dwpas_c_prd_dim.dim1_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim1OutValue(BigDecimal dim1OutValue) {
		this.dim1OutValue = dim1OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim2_code
	 * 
	 * @return the value of dwpas_c_prd_dim.dim2_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getDim2Code() {
		return dim2Code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim2_code
	 * 
	 * @param dim2Code
	 *            the value for dwpas_c_prd_dim.dim2_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim2Code(String dim2Code) {
		this.dim2Code = dim2Code == null ? null : dim2Code.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim2_in_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim2_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim2InValue() {
		return dim2InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim2_in_value
	 * 
	 * @param dim2InValue
	 *            the value for dwpas_c_prd_dim.dim2_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim2InValue(BigDecimal dim2InValue) {
		this.dim2InValue = dim2InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim2_out_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim2_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim2OutValue() {
		return dim2OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim2_out_value
	 * 
	 * @param dim2OutValue
	 *            the value for dwpas_c_prd_dim.dim2_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim2OutValue(BigDecimal dim2OutValue) {
		this.dim2OutValue = dim2OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim3_code
	 * 
	 * @return the value of dwpas_c_prd_dim.dim3_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getDim3Code() {
		return dim3Code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim3_code
	 * 
	 * @param dim3Code
	 *            the value for dwpas_c_prd_dim.dim3_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim3Code(String dim3Code) {
		this.dim3Code = dim3Code == null ? null : dim3Code.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim3_in_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim3_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim3InValue() {
		return dim3InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim3_in_value
	 * 
	 * @param dim3InValue
	 *            the value for dwpas_c_prd_dim.dim3_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim3InValue(BigDecimal dim3InValue) {
		this.dim3InValue = dim3InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim3_out_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim3_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim3OutValue() {
		return dim3OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim3_out_value
	 * 
	 * @param dim3OutValue
	 *            the value for dwpas_c_prd_dim.dim3_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim3OutValue(BigDecimal dim3OutValue) {
		this.dim3OutValue = dim3OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim4_code
	 * 
	 * @return the value of dwpas_c_prd_dim.dim4_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getDim4Code() {
		return dim4Code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim4_code
	 * 
	 * @param dim4Code
	 *            the value for dwpas_c_prd_dim.dim4_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim4Code(String dim4Code) {
		this.dim4Code = dim4Code == null ? null : dim4Code.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim4_in_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim4_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim4InValue() {
		return dim4InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim4_in_value
	 * 
	 * @param dim4InValue
	 *            the value for dwpas_c_prd_dim.dim4_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim4InValue(BigDecimal dim4InValue) {
		this.dim4InValue = dim4InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim4_out_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim4_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim4OutValue() {
		return dim4OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim4_out_value
	 * 
	 * @param dim4OutValue
	 *            the value for dwpas_c_prd_dim.dim4_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim4OutValue(BigDecimal dim4OutValue) {
		this.dim4OutValue = dim4OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim5_code
	 * 
	 * @return the value of dwpas_c_prd_dim.dim5_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getDim5Code() {
		return dim5Code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim5_code
	 * 
	 * @param dim5Code
	 *            the value for dwpas_c_prd_dim.dim5_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim5Code(String dim5Code) {
		this.dim5Code = dim5Code == null ? null : dim5Code.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim5_in_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim5_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim5InValue() {
		return dim5InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim5_in_value
	 * 
	 * @param dim5InValue
	 *            the value for dwpas_c_prd_dim.dim5_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim5InValue(BigDecimal dim5InValue) {
		this.dim5InValue = dim5InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim5_out_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim5_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim5OutValue() {
		return dim5OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim5_out_value
	 * 
	 * @param dim5OutValue
	 *            the value for dwpas_c_prd_dim.dim5_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim5OutValue(BigDecimal dim5OutValue) {
		this.dim5OutValue = dim5OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim6_code
	 * 
	 * @return the value of dwpas_c_prd_dim.dim6_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public String getDim6Code() {
		return dim6Code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim6_code
	 * 
	 * @param dim6Code
	 *            the value for dwpas_c_prd_dim.dim6_code
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim6Code(String dim6Code) {
		this.dim6Code = dim6Code == null ? null : dim6Code.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim6_in_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim6_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim6InValue() {
		return dim6InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim6_in_value
	 * 
	 * @param dim6InValue
	 *            the value for dwpas_c_prd_dim.dim6_in_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim6InValue(BigDecimal dim6InValue) {
		this.dim6InValue = dim6InValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.dim6_out_value
	 * 
	 * @return the value of dwpas_c_prd_dim.dim6_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public BigDecimal getDim6OutValue() {
		return dim6OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.dim6_out_value
	 * 
	 * @param dim6OutValue
	 *            the value for dwpas_c_prd_dim.dim6_out_value
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setDim6OutValue(BigDecimal dim6OutValue) {
		this.dim6OutValue = dim6OutValue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.GMT_CREATE
	 * 
	 * @return the value of dwpas_c_prd_dim.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.GMT_CREATE
	 * 
	 * @param gmtCreate
	 *            the value for dwpas_c_prd_dim.GMT_CREATE
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_prd_dim.GMT_MODIFIED
	 * 
	 * @return the value of dwpas_c_prd_dim.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_prd_dim.GMT_MODIFIED
	 * 
	 * @param gmtModified
	 *            the value for dwpas_c_prd_dim.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Tue Feb 21 12:07:34 CST 2012
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public String getDim1ValueUnit() {
		return dim1ValueUnit;
	}

	public void setDim1ValueUnit(String dim1ValueUnit) {
		this.dim1ValueUnit = dim1ValueUnit;
	}

	public String getDim2ValueUnit() {
		return dim2ValueUnit;
	}

	public void setDim2ValueUnit(String dim2ValueUnit) {
		this.dim2ValueUnit = dim2ValueUnit;
	}

	public String getDim3ValueUnit() {
		return dim3ValueUnit;
	}

	public void setDim3ValueUnit(String dim3ValueUnit) {
		this.dim3ValueUnit = dim3ValueUnit;
	}

	public String getDim4ValueUnit() {
		return dim4ValueUnit;
	}

	public void setDim4ValueUnit(String dim4ValueUnit) {
		this.dim4ValueUnit = dim4ValueUnit;
	}

	public String getDim5ValueUnit() {
		return dim5ValueUnit;
	}

	public void setDim5ValueUnit(String dim5ValueUnit) {
		this.dim5ValueUnit = dim5ValueUnit;
	}

	public String getDim6ValueUnit() {
		return dim6ValueUnit;
	}

	public void setDim6ValueUnit(String dim6ValueUnit) {
		this.dim6ValueUnit = dim6ValueUnit;
	}

	public String getDim1Name() {
		return dim1Name;
	}

	public void setDim1Name(String dim1Name) {
		this.dim1Name = dim1Name;
	}

	public String getDim2Name() {
		return dim2Name;
	}

	public void setDim2Name(String dim2Name) {
		this.dim2Name = dim2Name;
	}

	public String getDim3Name() {
		return dim3Name;
	}

	public void setDim3Name(String dim3Name) {
		this.dim3Name = dim3Name;
	}

	public String getDim4Name() {
		return dim4Name;
	}

	public void setDim4Name(String dim4Name) {
		this.dim4Name = dim4Name;
	}

	public String getDim5Name() {
		return dim5Name;
	}

	public void setDim5Name(String dim5Name) {
		this.dim5Name = dim5Name;
	}

	public String getDim6Name() {
		return dim6Name;
	}

	public void setDim6Name(String dim6Name) {
		this.dim6Name = dim6Name;
	}
}