package com.infosmart.portal.pojo;

import java.util.Date;

/**
 * 指标信息
 * 
 * @author infosmart
 * 
 */
public class DwpasCKpiInfo {
	/**
	 * 指标编码
	 */
	private String kpiCode;

	/**
	 * 父级编码
	 */
	private String parentCode;

	/**
	 * 指标名称
	 */
	private String kpiName;

	/**
	 * 显示名称
	 */
	private String dispName;

	/**
	 * 指标类型�?1-日统计指标；2-周统计指标；3-月统计指标
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	private String kpiType;
	/**
	 * 日统计指标
	 */
	public static final int KPI_TYPE_OF_DAY = 1;
	/**
	 * 周统计指标
	 */
	public static final int KPI_TYPE_OF_WEEK = 2;
	/**
	 * 月统计指标
	 */
	public static final int KPI_TYPE_OF_MONTH = 3;

	/**
	 * 指标描述
	 */
	private String kpiTypeDesc;

	/**
	 * 是否大盘指标
	 */
	private String isOverall;

	/**
	 * 是否显示
	 */
	private String isShow;

	/**
	 * 显示顺序
	 */
	private Short showOrder;

	/**
	 * 是否均值
	 */
	private String isAverage;

	/**
	 * 是否峰值
	 */
	private String isMax;

	/**
	 * 是否变化幅度值
	 */
	private String isVariation;

	/**
	 * 是否百分比指值
	 */
	private String isPercent;

	/**
	 * 换算单位
	 */
	private String unit;

	/**
	 * 换算小数位数
	 */
	private Short decimalNum;

	/**
	 * 换算位数
	 */
	private Short convertNum;

	/**
	 * 换算方式
	 */
	private String convertType;
	/**
	 * 乘法
	 */
	public static final int CONVERT_TYPE_MULTIPLY = 1;

	/**
	 * 除法
	 */
	public static final int CONVERT_TYPE_DIVIDE = 2;

	/**
	 * 是否计算指标
	 */
	private String isCalKpi;

	/**
	 * 计算规则公式
	 */
	private String roleFormula;

	/**
	 * 是否可用
	 */
	private String isUse;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	private Date gmtModified;

	private Boolean marked;

	private String parentName;

	public DwpasCKpiInfo() {
	}

	public DwpasCKpiInfo(String kpiCode, String kpiName) {
		super();
		this.kpiCode = kpiCode;
		this.kpiName = kpiName;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @return the value of dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getKpiCode() {
		return kpiCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @param kpiCode
	 *            the value for dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setKpiCode(String kpiCode) {
		this.kpiCode = kpiCode == null ? null : kpiCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.parent_code
	 * 
	 * @return the value of dwpas_c_kpi_info.parent_code
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getParentCode() {
		return parentCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.parent_code
	 * 
	 * @param parentCode
	 *            the value for dwpas_c_kpi_info.parent_code
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode == null ? null : parentCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.kpi_name
	 * 
	 * @return the value of dwpas_c_kpi_info.kpi_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getKpiName() {
		return kpiName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.kpi_name
	 * 
	 * @param kpiName
	 *            the value for dwpas_c_kpi_info.kpi_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setKpiName(String kpiName) {
		this.kpiName = kpiName == null ? null : kpiName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.disp_name
	 * 
	 * @return the value of dwpas_c_kpi_info.disp_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getDispName() {
		if (this.dispName == null || this.dispName.length() == 0
				|| "null".equalsIgnoreCase(this.dispName)) {
			this.dispName = this.kpiName;
		}
		return dispName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.disp_name
	 * 
	 * @param dispName
	 *            the value for dwpas_c_kpi_info.disp_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setDispName(String dispName) {
		this.dispName = dispName == null ? null : dispName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.kpi_type
	 * 
	 * @return the value of dwpas_c_kpi_info.kpi_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getKpiType() {
		return kpiType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.kpi_type
	 * 
	 * @param kpiType
	 *            the value for dwpas_c_kpi_info.kpi_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setKpiType(String kpiType) {
		this.kpiType = kpiType == null ? null : kpiType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_overall
	 * 
	 * @return the value of dwpas_c_kpi_info.is_overall
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsOverall() {
		return isOverall;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_overall
	 * 
	 * @param isOverall
	 *            the value for dwpas_c_kpi_info.is_overall
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsOverall(String isOverall) {
		this.isOverall = isOverall == null ? null : isOverall.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_show
	 * 
	 * @return the value of dwpas_c_kpi_info.is_show
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_show
	 * 
	 * @param isShow
	 *            the value for dwpas_c_kpi_info.is_show
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsShow(String isShow) {
		this.isShow = isShow == null ? null : isShow.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.show_order
	 * 
	 * @return the value of dwpas_c_kpi_info.show_order
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Short getShowOrder() {
		return showOrder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.show_order
	 * 
	 * @param showOrder
	 *            the value for dwpas_c_kpi_info.show_order
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setShowOrder(Short showOrder) {
		this.showOrder = showOrder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_average
	 * 
	 * @return the value of dwpas_c_kpi_info.is_average
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsAverage() {
		return isAverage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_average
	 * 
	 * @param isAverage
	 *            the value for dwpas_c_kpi_info.is_average
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsAverage(String isAverage) {
		this.isAverage = isAverage == null ? null : isAverage.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_max
	 * 
	 * @return the value of dwpas_c_kpi_info.is_max
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsMax() {
		return isMax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_max
	 * 
	 * @param isMax
	 *            the value for dwpas_c_kpi_info.is_max
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsMax(String isMax) {
		this.isMax = isMax == null ? null : isMax.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_variation
	 * 
	 * @return the value of dwpas_c_kpi_info.is_variation
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsVariation() {
		return isVariation;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_variation
	 * 
	 * @param isVariation
	 *            the value for dwpas_c_kpi_info.is_variation
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsVariation(String isVariation) {
		this.isVariation = isVariation == null ? null : isVariation.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_percent
	 * 
	 * @return the value of dwpas_c_kpi_info.is_percent
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsPercent() {
		return isPercent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_percent
	 * 
	 * @param isPercent
	 *            the value for dwpas_c_kpi_info.is_percent
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsPercent(String isPercent) {
		this.isPercent = isPercent == null ? null : isPercent.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.unit
	 * 
	 * @return the value of dwpas_c_kpi_info.unit
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.unit
	 * 
	 * @param unit
	 *            the value for dwpas_c_kpi_info.unit
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.decimal_num
	 * 
	 * @return the value of dwpas_c_kpi_info.decimal_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Short getDecimalNum() {
		return decimalNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.decimal_num
	 * 
	 * @param decimalNum
	 *            the value for dwpas_c_kpi_info.decimal_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setDecimalNum(Short decimalNum) {
		this.decimalNum = decimalNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.convert_num
	 * 
	 * @return the value of dwpas_c_kpi_info.convert_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Short getConvertNum() {
		return convertNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.convert_num
	 * 
	 * @param convertNum
	 *            the value for dwpas_c_kpi_info.convert_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setConvertNum(Short convertNum) {
		this.convertNum = convertNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.convert_type
	 * 
	 * @return the value of dwpas_c_kpi_info.convert_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getConvertType() {
		return convertType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.convert_type
	 * 
	 * @param convertType
	 *            the value for dwpas_c_kpi_info.convert_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setConvertType(String convertType) {
		this.convertType = convertType == null ? null : convertType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @return the value of dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsCalKpi() {
		return isCalKpi;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @param isCalKpi
	 *            the value for dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsCalKpi(String isCalKpi) {
		this.isCalKpi = isCalKpi == null ? null : isCalKpi.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.role_formula
	 * 
	 * @return the value of dwpas_c_kpi_info.role_formula
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getRoleFormula() {
		return roleFormula;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.role_formula
	 * 
	 * @param roleFormula
	 *            the value for dwpas_c_kpi_info.role_formula
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setRoleFormula(String roleFormula) {
		this.roleFormula = roleFormula == null ? null : roleFormula.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_use
	 * 
	 * @return the value of dwpas_c_kpi_info.is_use
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_use
	 * 
	 * @param isUse
	 *            the value for dwpas_c_kpi_info.is_use
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsUse(String isUse) {
		this.isUse = isUse == null ? null : isUse.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @return the value of dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @param gmtCreate
	 *            the value for dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @return the value of dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @param gmtModified
	 *            the value for dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public Boolean getMarked() {
		return marked;
	}

	public void setMarked(Boolean marked) {
		this.marked = marked;
	}

	public String getKpiTypeDesc() {
		try {
			int kpiTypeVal = Integer.parseInt(this.kpiType);
			switch (kpiTypeVal) {
			case KPI_TYPE_OF_DAY:
				this.kpiTypeDesc = "日指标";
				break;
			case KPI_TYPE_OF_WEEK:
				this.kpiTypeDesc = "周指标";
				break;
			default:
				this.kpiTypeDesc = "月指标";
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return kpiTypeDesc;
	}
}