package com.infosmart.po;

/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>DWPAS_C_COM_KPI_INFO</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_c_com_kpi_info.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class ComKpiInfo {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>COM_KPI_CODE</tt>.
	 */
	private String comKpiCode;

	/**
	 * This property corresponds to db column <tt>COM_KPI_NAME</tt>.
	 */
	private String comKpiName;

	/**
	 * This property corresponds to db column <tt>IS_SHOW_RANK</tt>.
	 */
	private String isShowRank;

	/**
	 * This property corresponds to db column <tt>RANK_SHOW_ORDER</tt>.
	 */
	private int rankShowOrder;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;
	private String codes;
	private String keyWord1;
	private String keyWord2;
	
	//xbb添加
	private String productId;
	private String productName;
	
	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getKeyWord1() {
		return keyWord1;
	}

	public void setKeyWord1(String keyWord1) {
		this.keyWord1 = keyWord1;
	}

	public String getKeyWord2() {
		return keyWord2;
	}

	public void setKeyWord2(String keyWord2) {
		this.keyWord2 = keyWord2;
	}

	public String getCodes() {
		return codes;
	}

	public void setCodes(String codes) {
		this.codes = codes;
	}

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;
	private String operFlag;
	private Page page;
	public Page getPage() {
		if (page == null)
			page = new Page();
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}
    //========== getters and setters ==========

    public String getOperFlag() {
		return operFlag;
	}

	public void setOperFlag(String operFlag) {
		this.operFlag = operFlag;
	}

	/**
     * Getter method for property <tt>comKpiCode</tt>.
     *
     * @return property value of comKpiCode
     */
	public String getComKpiCode() {
		return comKpiCode;
	}
	
	/**
	 * Setter method for property <tt>comKpiCode</tt>.
	 * 
	 * @param comKpiCode value to be assigned to property comKpiCode
     */
	public void setComKpiCode(String comKpiCode) {
		this.comKpiCode = comKpiCode;
	}

    /**
     * Getter method for property <tt>comKpiName</tt>.
     *
     * @return property value of comKpiName
     */
	public String getComKpiName() {
		return comKpiName;
	}
	
	/**
	 * Setter method for property <tt>comKpiName</tt>.
	 * 
	 * @param comKpiName value to be assigned to property comKpiName
     */
	public void setComKpiName(String comKpiName) {
		this.comKpiName = comKpiName;
	}

    /**
     * Getter method for property <tt>isShowRank</tt>.
     *
     * @return property value of isShowRank
     */
	public String getIsShowRank() {
		return isShowRank;
	}
	
	/**
	 * Setter method for property <tt>isShowRank</tt>.
	 * 
	 * @param isShowRank value to be assigned to property isShowRank
     */
	public void setIsShowRank(String isShowRank) {
		this.isShowRank = isShowRank;
	}

    /**
     * Getter method for property <tt>rankShowOrder</tt>.
     *
     * @return property value of rankShowOrder
     */
	public int getRankShowOrder() {
		return rankShowOrder;
	}
	
	/**
	 * Setter method for property <tt>rankShowOrder</tt>.
	 * 
	 * @param rankShowOrder value to be assigned to property rankShowOrder
     */
	public void setRankShowOrder(int rankShowOrder) {
		this.rankShowOrder = rankShowOrder;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}

