package com.infosmart.po;

import java.io.Serializable;
import java.util.Date;

/**
 * 指标信息
 * 
 * @author Administrator
 * 
 */
public class DwpasCKpiInfo {
	/**
	 * 指标编码
	 */
	private String kpiCode;

	/**
	 * 父级编码
	 */
	private String parentCode;

	/**
	 * 指标名称
	 */
	private String kpiName;

	/**
	 * 显示名称
	 */
	private String dispName;

	/**
	 * 指标类型�?1-日统计指标；2-周统计指标；3-月统计指标
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	private String kpiType;
	/**
	 * 日统计指标
	 */
	public static final int KPI_TYPE_OF_DAY = 1;
	/**
	 * 周统计指标
	 */
	public static final int KPI_TYPE_OF_WEEK = 2;
	/**
	 * 月统计指标
	 */
	public static final int KPI_TYPE_OF_MONTH = 3;

	/**
	 * 指标描述
	 */
	private String kpiTypeDesc;

	/**
	 * 是否大盘指标
	 */
	private String isOverall;

	/**
	 * 是否显示
	 */
	private String isShow;

	/**
	 * 显示顺序
	 */
	private Short showOrder;

	/**
	 * 是否均值
	 */
	private String isAverage;

	/**
	 * 是否峰值
	 */
	private String isMax;

	/**
	 * 是否变化幅度值
	 */
	private String isVariation;

	/**
	 * 是否百分比指值
	 */
	private String isPercent;

	/**
	 * 换算单位
	 */
	private String unit;

	/**
	 * 换算小数位数
	 */
	private Short decimalNum;

	/**
	 * 换算位数
	 */
	private Short convertNum;

	/**
	 * 换算方式
	 */
	private String convertType;
	/**
	 * 乘法
	 */
	public static final int CONVERT_TYPE_MULTIPLY = 1;

	/**
	 * 除法
	 */
	public static final int CONVERT_TYPE_DIVIDE = 2;

	/**
	 * 是否计算指标
	 */
	private String isCalKpi;

	/**
	 * 计算规则公式
	 */
	private String roleFormula;

	/**
	 * 是否可用
	 */
	private String isUse;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	private Date gmtModified;

	/**
	 * 指标类型
	 */
	private Integer typeId;

	/**
	 * 指标单位
	 */
	private Integer unitId;

	/**
	 * 指标单位字符
	 */
	private String unitStr;

	/**
	 * 指标单位字符（跟随在KPI Name后面的，形如 生活助手新增用户数(万)，这里的 (万)
	 */
	private String unitStrPost;

	/**
	 * 指标说明
	 */
	private String detail;

	/**
	 * 指标口径
	 */
	private String kpiRestrict;

	/**
	 * 时间口径
	 */
	private String restrictTime;

	/**
	 * 关联表名
	 */
	private String relateTable;

	/**
	 * 关联表名描述
	 */
	private String relateTableDes;

	/**
	 * 创建者
	 */
	private String createUser;

	/**
	 * 创建时间
	 */
	private Date createDate;

	/**
	 * 绩效类别
	 */
	private Integer goalType;

	/**
	 * 一级指标类别
	 */
	private Integer levelTypeOne;

	/**
	 * 二级指标类别
	 */
	private Integer levelTypeTwo;

	/**
	 * 是否首页显示描述
	 */
	private Integer isShowDesc;

	/**
	 * 时间粒度定义
	 */
	private String period;

	/**
	 * 业务类型展示定义
	 */
	private String businessType;

	/**
	 * 指标展现名称
	 */
	private String kpiNameShow;

	/**
	 * 指标数量级ID
	 */
	private Integer sizeId;

	/**
	 * 指标关联指标
	 */
	private String linkedKpiID;

	/**
	 * 部门ID
	 */
	private Integer depId;

	/**
	 * 事件ID
	 */
	private Serializable eventId;

	/**
	 * 日粒度偏差
	 */
	private Integer dayOffset;

	/**
	 * KPI绩效名称
	 */
	private String kpiNameKPI;

	/**
	 * 是否在详情页面锁定数据范围的标识
	 */
	private Integer isDataRangeFix;

	/**
	 * 锁定数据范围的下限
	 */
	private Double dataRangeBottom;

	/**
	 * 锁定数据范围的上限
	 */
	private Double dataRangeTop;

	/**
	 * 通用指标Code
	 */
	private String ComKpiCode;
	private String productId;

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getComKpiCode() {
		return ComKpiCode;
	}

	public void setComKpiCode(String comKpiCode) {
		ComKpiCode = comKpiCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @return the value of dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getKpiCode() {
		return kpiCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @param kpiCode
	 *            the value for dwpas_c_kpi_info.KPI_CODE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setKpiCode(String kpiCode) {
		this.kpiCode = kpiCode == null ? null : kpiCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.parent_code
	 * 
	 * @return the value of dwpas_c_kpi_info.parent_code
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getParentCode() {
		return parentCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.parent_code
	 * 
	 * @param parentCode
	 *            the value for dwpas_c_kpi_info.parent_code
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode == null ? null : parentCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.kpi_name
	 * 
	 * @return the value of dwpas_c_kpi_info.kpi_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getKpiName() {
		return kpiName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.kpi_name
	 * 
	 * @param kpiName
	 *            the value for dwpas_c_kpi_info.kpi_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setKpiName(String kpiName) {
		this.kpiName = kpiName == null ? null : kpiName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.disp_name
	 * 
	 * @return the value of dwpas_c_kpi_info.disp_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getDispName() {
		return dispName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.disp_name
	 * 
	 * @param dispName
	 *            the value for dwpas_c_kpi_info.disp_name
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setDispName(String dispName) {
		this.dispName = dispName == null ? null : dispName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.kpi_type
	 * 
	 * @return the value of dwpas_c_kpi_info.kpi_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getKpiType() {
		return kpiType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.kpi_type
	 * 
	 * @param kpiType
	 *            the value for dwpas_c_kpi_info.kpi_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setKpiType(String kpiType) {
		this.kpiType = kpiType == null ? null : kpiType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_overall
	 * 
	 * @return the value of dwpas_c_kpi_info.is_overall
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsOverall() {
		return isOverall;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_overall
	 * 
	 * @param isOverall
	 *            the value for dwpas_c_kpi_info.is_overall
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsOverall(String isOverall) {
		this.isOverall = isOverall == null ? null : isOverall.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_show
	 * 
	 * @return the value of dwpas_c_kpi_info.is_show
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsShow() {
		return isShow;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_show
	 * 
	 * @param isShow
	 *            the value for dwpas_c_kpi_info.is_show
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsShow(String isShow) {
		this.isShow = isShow == null ? null : isShow.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.show_order
	 * 
	 * @return the value of dwpas_c_kpi_info.show_order
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Short getShowOrder() {
		return showOrder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.show_order
	 * 
	 * @param showOrder
	 *            the value for dwpas_c_kpi_info.show_order
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setShowOrder(Short showOrder) {
		this.showOrder = showOrder;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_average
	 * 
	 * @return the value of dwpas_c_kpi_info.is_average
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsAverage() {
		return isAverage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_average
	 * 
	 * @param isAverage
	 *            the value for dwpas_c_kpi_info.is_average
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsAverage(String isAverage) {
		this.isAverage = isAverage == null ? null : isAverage.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_max
	 * 
	 * @return the value of dwpas_c_kpi_info.is_max
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsMax() {
		return isMax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_max
	 * 
	 * @param isMax
	 *            the value for dwpas_c_kpi_info.is_max
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsMax(String isMax) {
		this.isMax = isMax == null ? null : isMax.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_variation
	 * 
	 * @return the value of dwpas_c_kpi_info.is_variation
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsVariation() {
		return isVariation;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_variation
	 * 
	 * @param isVariation
	 *            the value for dwpas_c_kpi_info.is_variation
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsVariation(String isVariation) {
		this.isVariation = isVariation == null ? null : isVariation.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_percent
	 * 
	 * @return the value of dwpas_c_kpi_info.is_percent
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsPercent() {
		return isPercent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_percent
	 * 
	 * @param isPercent
	 *            the value for dwpas_c_kpi_info.is_percent
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsPercent(String isPercent) {
		this.isPercent = isPercent == null ? null : isPercent.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.unit
	 * 
	 * @return the value of dwpas_c_kpi_info.unit
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.unit
	 * 
	 * @param unit
	 *            the value for dwpas_c_kpi_info.unit
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.decimal_num
	 * 
	 * @return the value of dwpas_c_kpi_info.decimal_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Short getDecimalNum() {
		return decimalNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.decimal_num
	 * 
	 * @param decimalNum
	 *            the value for dwpas_c_kpi_info.decimal_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setDecimalNum(Short decimalNum) {
		this.decimalNum = decimalNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.convert_num
	 * 
	 * @return the value of dwpas_c_kpi_info.convert_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Short getConvertNum() {
		return convertNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.convert_num
	 * 
	 * @param convertNum
	 *            the value for dwpas_c_kpi_info.convert_num
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setConvertNum(Short convertNum) {
		this.convertNum = convertNum;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.convert_type
	 * 
	 * @return the value of dwpas_c_kpi_info.convert_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getConvertType() {
		return convertType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.convert_type
	 * 
	 * @param convertType
	 *            the value for dwpas_c_kpi_info.convert_type
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setConvertType(String convertType) {
		this.convertType = convertType == null ? null : convertType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @return the value of dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsCalKpi() {
		return isCalKpi;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @param isCalKpi
	 *            the value for dwpas_c_kpi_info.is_cal_kpi
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsCalKpi(String isCalKpi) {
		this.isCalKpi = isCalKpi == null ? null : isCalKpi.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.role_formula
	 * 
	 * @return the value of dwpas_c_kpi_info.role_formula
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getRoleFormula() {
		return roleFormula;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.role_formula
	 * 
	 * @param roleFormula
	 *            the value for dwpas_c_kpi_info.role_formula
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setRoleFormula(String roleFormula) {
		this.roleFormula = roleFormula == null ? null : roleFormula.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.is_use
	 * 
	 * @return the value of dwpas_c_kpi_info.is_use
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public String getIsUse() {
		return isUse;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.is_use
	 * 
	 * @param isUse
	 *            the value for dwpas_c_kpi_info.is_use
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setIsUse(String isUse) {
		this.isUse = isUse == null ? null : isUse.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @return the value of dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @param gmtCreate
	 *            the value for dwpas_c_kpi_info.GMT_CREATE
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @return the value of dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @param gmtModified
	 *            the value for dwpas_c_kpi_info.GMT_MODIFIED
	 * 
	 * @ibatorgenerated Mon Feb 20 17:20:52 CST 2012
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public String getKpiTypeDesc() {
		try {
			if (this.kpiType != null) {
				int kpiTypeVal = Integer.parseInt(this.kpiType);
				switch (kpiTypeVal) {
				case KPI_TYPE_OF_DAY:
					this.kpiTypeDesc = "日指标";
					break;
				case KPI_TYPE_OF_WEEK:
					this.kpiTypeDesc = "周指标";
					break;
				default:
					this.kpiTypeDesc = "月指标";
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return kpiTypeDesc;
	}

	public Integer getTypeId() {
		return typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public Integer getUnitId() {
		return unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	public String getUnitStr() {
		return unitStr;
	}

	public void setUnitStr(String unitStr) {
		this.unitStr = unitStr;
	}

	public String getUnitStrPost() {
		return unitStrPost;
	}

	public void setUnitStrPost(String unitStrPost) {
		this.unitStrPost = unitStrPost;
	}

	public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getKpiRestrict() {
		return kpiRestrict;
	}

	public void setKpiRestrict(String kpiRestrict) {
		this.kpiRestrict = kpiRestrict;
	}

	public String getRestrictTime() {
		return restrictTime;
	}

	public void setRestrictTime(String restrictTime) {
		this.restrictTime = restrictTime;
	}

	public String getRelateTable() {
		return relateTable;
	}

	public void setRelateTable(String relateTable) {
		this.relateTable = relateTable;
	}

	public String getRelateTableDes() {
		return relateTableDes;
	}

	public void setRelateTableDes(String relateTableDes) {
		this.relateTableDes = relateTableDes;
	}

	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getGoalType() {
		return goalType;
	}

	public void setGoalType(Integer goalType) {
		this.goalType = goalType;
	}

	public Integer getLevelTypeOne() {
		return levelTypeOne;
	}

	public void setLevelTypeOne(Integer levelTypeOne) {
		this.levelTypeOne = levelTypeOne;
	}

	public Integer getLevelTypeTwo() {
		return levelTypeTwo;
	}

	public void setLevelTypeTwo(Integer levelTypeTwo) {
		this.levelTypeTwo = levelTypeTwo;
	}

	public Integer getIsShowDesc() {
		return isShowDesc;
	}

	public void setIsShowDesc(Integer isShowDesc) {
		this.isShowDesc = isShowDesc;
	}

	public String getPeriod() {
		return period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	public String getKpiNameShow() {
		return kpiNameShow;
	}

	public void setKpiNameShow(String kpiNameShow) {
		this.kpiNameShow = kpiNameShow;
	}

	public Integer getSizeId() {
		return sizeId;
	}

	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}

	public String getLinkedKpiID() {
		return linkedKpiID;
	}

	public void setLinkedKpiID(String linkedKpiID) {
		this.linkedKpiID = linkedKpiID;
	}

	public Integer getDepId() {
		return depId;
	}

	public void setDepId(Integer depId) {
		this.depId = depId;
	}

	public Serializable getEventId() {
		return eventId;
	}

	public void setEventId(Serializable eventId) {
		this.eventId = eventId;
	}

	public Integer getDayOffset() {
		return dayOffset;
	}

	public void setDayOffset(Integer dayOffset) {
		this.dayOffset = dayOffset;
	}

	public String getKpiNameKPI() {
		return kpiNameKPI;
	}

	public void setKpiNameKPI(String kpiNameKPI) {
		this.kpiNameKPI = kpiNameKPI;
	}

	public Integer getIsDataRangeFix() {
		return isDataRangeFix;
	}

	public void setIsDataRangeFix(Integer isDataRangeFix) {
		this.isDataRangeFix = isDataRangeFix;
	}

	public Double getDataRangeBottom() {
		return dataRangeBottom;
	}

	public void setDataRangeBottom(Double dataRangeBottom) {
		this.dataRangeBottom = dataRangeBottom;
	}

	public Double getDataRangeTop() {
		return dataRangeTop;
	}

	public void setDataRangeTop(Double dataRangeTop) {
		this.dataRangeTop = dataRangeTop;
	}

	public void setKpiTypeDesc(String kpiTypeDesc) {
		this.kpiTypeDesc = kpiTypeDesc;
	}

}
