package com.infosmart.po;

/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>DWPAS_C_SYS_TYPE</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_c_sys_type.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class MisTypeInfo {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>TYPE_ID</tt>.
	 */
	private String typeId;

	/**
	 * This property corresponds to db column <tt>GROUP_ID</tt>.
	 */
	private String groupId;

	/**
	 * This property corresponds to db column <tt>TYPE_NAME</tt>.
	 */
	private String typeName;

	/**
	 * This property corresponds to db column <tt>DETAIL</tt>.
	 */
	private String detail;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>typeId</tt>.
     *
     * @return property value of typeId
     */
	private String isDelete;
	
	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	private Page page;
	public Page getPage() {
		if (page == null)
			page = new Page();
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	/**
	 * Setter method for property <tt>typeId</tt>.
	 * 
	 * @param typeId value to be assigned to property typeId
     */
	

    /**
     * Getter method for property <tt>groupId</tt>.
     *
     * @return property value of groupId
     */
	public String getGroupId() {
		return groupId;
	}
	
	public String getTypeId() {
		return typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	/**
	 * Setter method for property <tt>groupId</tt>.
	 * 
	 * @param groupId value to be assigned to property groupId
     */
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

    /**
     * Getter method for property <tt>typeName</tt>.
     *
     * @return property value of typeName
     */
	public String getTypeName() {
		return typeName;
	}
	
	/**
	 * Setter method for property <tt>typeName</tt>.
	 * 
	 * @param typeName value to be assigned to property typeName
     */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

    /**
     * Getter method for property <tt>detail</tt>.
     *
     * @return property value of detail
     */
	public String getDetail() {
		return detail;
	}
	
	/**
	 * Setter method for property <tt>detail</tt>.
	 * 
	 * @param detail value to be assigned to property detail
     */
	public void setDetail(String detail) {
		this.detail = detail;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}

