package com.infosmart.po;

public class OdsExtChannelInputs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.CHANNEL
     *
     * @mbggenerated
     */
    private String channel;
    
    private String kpiNum;

    public String getKpiNum() {
		return kpiNum;
	}

	public void setKpiNum(String kpiNum) {
		this.kpiNum = kpiNum;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.KPI_DEP
     *
     * @mbggenerated
     */
    private String kpiDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.THROWIN_START
     *
     * @mbggenerated
     */
    private String throwinStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.THROWIN_END
     *
     * @mbggenerated
     */
    private String throwinEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.KPI_CODE
     *
     * @mbggenerated
     */
    private String kpiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.THROWIN_RANGE
     *
     * @mbggenerated
     */
    private String throwinRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    private String currComValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_channel_inputs.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.CHANNEL
     *
     * @return the value of ods_ext_channel_inputs.CHANNEL
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.CHANNEL
     *
     * @param channel the value for ods_ext_channel_inputs.CHANNEL
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.KPI_DEP
     *
     * @return the value of ods_ext_channel_inputs.KPI_DEP
     *
     * @mbggenerated
     */
    public String getKpiDep() {
        return kpiDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.KPI_DEP
     *
     * @param kpiDep the value for ods_ext_channel_inputs.KPI_DEP
     *
     * @mbggenerated
     */
    public void setKpiDep(String kpiDep) {
        this.kpiDep = kpiDep == null ? null : kpiDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.THROWIN_START
     *
     * @return the value of ods_ext_channel_inputs.THROWIN_START
     *
     * @mbggenerated
     */
    public String getThrowinStart() {
        return throwinStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.THROWIN_START
     *
     * @param throwinStart the value for ods_ext_channel_inputs.THROWIN_START
     *
     * @mbggenerated
     */
    public void setThrowinStart(String throwinStart) {
        this.throwinStart = throwinStart == null ? null : throwinStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.THROWIN_END
     *
     * @return the value of ods_ext_channel_inputs.THROWIN_END
     *
     * @mbggenerated
     */
    public String getThrowinEnd() {
        return throwinEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.THROWIN_END
     *
     * @param throwinEnd the value for ods_ext_channel_inputs.THROWIN_END
     *
     * @mbggenerated
     */
    public void setThrowinEnd(String throwinEnd) {
        this.throwinEnd = throwinEnd == null ? null : throwinEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.KPI_CODE
     *
     * @return the value of ods_ext_channel_inputs.KPI_CODE
     *
     * @mbggenerated
     */
    public String getKpiCode() {
        return kpiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.KPI_CODE
     *
     * @param kpiCode the value for ods_ext_channel_inputs.KPI_CODE
     *
     * @mbggenerated
     */
    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode == null ? null : kpiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.THROWIN_RANGE
     *
     * @return the value of ods_ext_channel_inputs.THROWIN_RANGE
     *
     * @mbggenerated
     */
    public String getThrowinRange() {
        return throwinRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.THROWIN_RANGE
     *
     * @param throwinRange the value for ods_ext_channel_inputs.THROWIN_RANGE
     *
     * @mbggenerated
     */
    public void setThrowinRange(String throwinRange) {
        this.throwinRange = throwinRange == null ? null : throwinRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.CURR_COM_VALUE
     *
     * @return the value of ods_ext_channel_inputs.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    public String getCurrComValue() {
        return currComValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.CURR_COM_VALUE
     *
     * @param currComValue the value for ods_ext_channel_inputs.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    public void setCurrComValue(String currComValue) {
        this.currComValue = currComValue == null ? null : currComValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_channel_inputs.UNIT
     *
     * @return the value of ods_ext_channel_inputs.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_channel_inputs.UNIT
     *
     * @param unit the value for ods_ext_channel_inputs.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}