package com.infosmart.po;

public class OdsExtCompetitorsSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.COMPETITORS
     *
     * @mbggenerated
     */
    private String competitors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.KPI_NUM
     *
     * @mbggenerated
     */
    private String kpiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.KPI_DEP
     *
     * @mbggenerated
     */
    private String kpiDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.KPI_YM
     *
     * @mbggenerated
     */
    private String kpiYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.KPI_CODE
     *
     * @mbggenerated
     */
    private String kpiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    private String currComValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_competitors_sales.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.COMPETITORS
     *
     * @return the value of ods_ext_competitors_sales.COMPETITORS
     *
     * @mbggenerated
     */
    public String getCompetitors() {
        return competitors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.COMPETITORS
     *
     * @param competitors the value for ods_ext_competitors_sales.COMPETITORS
     *
     * @mbggenerated
     */
    public void setCompetitors(String competitors) {
        this.competitors = competitors == null ? null : competitors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.KPI_NUM
     *
     * @return the value of ods_ext_competitors_sales.KPI_NUM
     *
     * @mbggenerated
     */
    public String getKpiNum() {
        return kpiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.KPI_NUM
     *
     * @param kpiNum the value for ods_ext_competitors_sales.KPI_NUM
     *
     * @mbggenerated
     */
    public void setKpiNum(String kpiNum) {
        this.kpiNum = kpiNum == null ? null : kpiNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.KPI_DEP
     *
     * @return the value of ods_ext_competitors_sales.KPI_DEP
     *
     * @mbggenerated
     */
    public String getKpiDep() {
        return kpiDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.KPI_DEP
     *
     * @param kpiDep the value for ods_ext_competitors_sales.KPI_DEP
     *
     * @mbggenerated
     */
    public void setKpiDep(String kpiDep) {
        this.kpiDep = kpiDep == null ? null : kpiDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.KPI_YM
     *
     * @return the value of ods_ext_competitors_sales.KPI_YM
     *
     * @mbggenerated
     */
    public String getKpiYm() {
        return kpiYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.KPI_YM
     *
     * @param kpiYm the value for ods_ext_competitors_sales.KPI_YM
     *
     * @mbggenerated
     */
    public void setKpiYm(String kpiYm) {
        this.kpiYm = kpiYm == null ? null : kpiYm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.KPI_CODE
     *
     * @return the value of ods_ext_competitors_sales.KPI_CODE
     *
     * @mbggenerated
     */
    public String getKpiCode() {
        return kpiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.KPI_CODE
     *
     * @param kpiCode the value for ods_ext_competitors_sales.KPI_CODE
     *
     * @mbggenerated
     */
    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode == null ? null : kpiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.CURR_COM_VALUE
     *
     * @return the value of ods_ext_competitors_sales.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    public String getCurrComValue() {
        return currComValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.CURR_COM_VALUE
     *
     * @param currComValue the value for ods_ext_competitors_sales.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    public void setCurrComValue(String currComValue) {
        this.currComValue = currComValue == null ? null : currComValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_competitors_sales.UNIT
     *
     * @return the value of ods_ext_competitors_sales.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_competitors_sales.UNIT
     *
     * @param unit the value for ods_ext_competitors_sales.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}