package com.infosmart.po;

public class OdsExtKpiInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_NAME
     *
     * @mbggenerated
     */
    private String kpiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_NUM
     *
     * @mbggenerated
     */
    private String kpiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_DEP
     *
     * @mbggenerated
     */
    private String kpiDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_YM
     *
     * @mbggenerated
     */
    private String kpiYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_CODE
     *
     * @mbggenerated
     */
    private String kpiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.COMPLETE_RATE
     *
     * @mbggenerated
     */
    private String completeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    private String currComValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.PRED_COM_VALUE
     *
     * @mbggenerated
     */
    private String predComValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.DATA_SOURCE
     *
     * @mbggenerated
     */
    private String dataSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.FIRST_KPI
     *
     * @mbggenerated
     */
    private String firstKpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.SECOND_KPI
     *
     * @mbggenerated
     */
    private String secondKpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.THREE_KPI
     *
     * @mbggenerated
     */
    private String threeKpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.SCOPE
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.STANDARD
     *
     * @mbggenerated
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.PURPOSES
     *
     * @mbggenerated
     */
    private String purposes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.WEIGHTS
     *
     * @mbggenerated
     */
    private String weights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_DEF
     *
     * @mbggenerated
     */
    private String kpiDef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_kpi_info.KPI_MEMO
     *
     * @mbggenerated
     */
    private String kpiMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_NAME
     *
     * @return the value of ods_ext_kpi_info.KPI_NAME
     *
     * @mbggenerated
     */
    public String getKpiName() {
        return kpiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_NAME
     *
     * @param kpiName the value for ods_ext_kpi_info.KPI_NAME
     *
     * @mbggenerated
     */
    public void setKpiName(String kpiName) {
        this.kpiName = kpiName == null ? null : kpiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_NUM
     *
     * @return the value of ods_ext_kpi_info.KPI_NUM
     *
     * @mbggenerated
     */
    public String getKpiNum() {
        return kpiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_NUM
     *
     * @param kpiNum the value for ods_ext_kpi_info.KPI_NUM
     *
     * @mbggenerated
     */
    public void setKpiNum(String kpiNum) {
        this.kpiNum = kpiNum == null ? null : kpiNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_DEP
     *
     * @return the value of ods_ext_kpi_info.KPI_DEP
     *
     * @mbggenerated
     */
    public String getKpiDep() {
        return kpiDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_DEP
     *
     * @param kpiDep the value for ods_ext_kpi_info.KPI_DEP
     *
     * @mbggenerated
     */
    public void setKpiDep(String kpiDep) {
        this.kpiDep = kpiDep == null ? null : kpiDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_YM
     *
     * @return the value of ods_ext_kpi_info.KPI_YM
     *
     * @mbggenerated
     */
    public String getKpiYm() {
        return kpiYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_YM
     *
     * @param kpiYm the value for ods_ext_kpi_info.KPI_YM
     *
     * @mbggenerated
     */
    public void setKpiYm(String kpiYm) {
        this.kpiYm = kpiYm == null ? null : kpiYm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_CODE
     *
     * @return the value of ods_ext_kpi_info.KPI_CODE
     *
     * @mbggenerated
     */
    public String getKpiCode() {
        return kpiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_CODE
     *
     * @param kpiCode the value for ods_ext_kpi_info.KPI_CODE
     *
     * @mbggenerated
     */
    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode == null ? null : kpiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.COMPLETE_RATE
     *
     * @return the value of ods_ext_kpi_info.COMPLETE_RATE
     *
     * @mbggenerated
     */
    public String getCompleteRate() {
        return completeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.COMPLETE_RATE
     *
     * @param completeRate the value for ods_ext_kpi_info.COMPLETE_RATE
     *
     * @mbggenerated
     */
    public void setCompleteRate(String completeRate) {
        this.completeRate = completeRate == null ? null : completeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.CURR_COM_VALUE
     *
     * @return the value of ods_ext_kpi_info.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    public String getCurrComValue() {
        return currComValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.CURR_COM_VALUE
     *
     * @param currComValue the value for ods_ext_kpi_info.CURR_COM_VALUE
     *
     * @mbggenerated
     */
    public void setCurrComValue(String currComValue) {
        this.currComValue = currComValue == null ? null : currComValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.PRED_COM_VALUE
     *
     * @return the value of ods_ext_kpi_info.PRED_COM_VALUE
     *
     * @mbggenerated
     */
    public String getPredComValue() {
        return predComValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.PRED_COM_VALUE
     *
     * @param predComValue the value for ods_ext_kpi_info.PRED_COM_VALUE
     *
     * @mbggenerated
     */
    public void setPredComValue(String predComValue) {
        this.predComValue = predComValue == null ? null : predComValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.UNIT
     *
     * @return the value of ods_ext_kpi_info.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.UNIT
     *
     * @param unit the value for ods_ext_kpi_info.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.DATA_SOURCE
     *
     * @return the value of ods_ext_kpi_info.DATA_SOURCE
     *
     * @mbggenerated
     */
    public String getDataSource() {
        return dataSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.DATA_SOURCE
     *
     * @param dataSource the value for ods_ext_kpi_info.DATA_SOURCE
     *
     * @mbggenerated
     */
    public void setDataSource(String dataSource) {
        this.dataSource = dataSource == null ? null : dataSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.FIRST_KPI
     *
     * @return the value of ods_ext_kpi_info.FIRST_KPI
     *
     * @mbggenerated
     */
    public String getFirstKpi() {
        return firstKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.FIRST_KPI
     *
     * @param firstKpi the value for ods_ext_kpi_info.FIRST_KPI
     *
     * @mbggenerated
     */
    public void setFirstKpi(String firstKpi) {
        this.firstKpi = firstKpi == null ? null : firstKpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.SECOND_KPI
     *
     * @return the value of ods_ext_kpi_info.SECOND_KPI
     *
     * @mbggenerated
     */
    public String getSecondKpi() {
        return secondKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.SECOND_KPI
     *
     * @param secondKpi the value for ods_ext_kpi_info.SECOND_KPI
     *
     * @mbggenerated
     */
    public void setSecondKpi(String secondKpi) {
        this.secondKpi = secondKpi == null ? null : secondKpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.THREE_KPI
     *
     * @return the value of ods_ext_kpi_info.THREE_KPI
     *
     * @mbggenerated
     */
    public String getThreeKpi() {
        return threeKpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.THREE_KPI
     *
     * @param threeKpi the value for ods_ext_kpi_info.THREE_KPI
     *
     * @mbggenerated
     */
    public void setThreeKpi(String threeKpi) {
        this.threeKpi = threeKpi == null ? null : threeKpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.SCOPE
     *
     * @return the value of ods_ext_kpi_info.SCOPE
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.SCOPE
     *
     * @param scope the value for ods_ext_kpi_info.SCOPE
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.STANDARD
     *
     * @return the value of ods_ext_kpi_info.STANDARD
     *
     * @mbggenerated
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.STANDARD
     *
     * @param standard the value for ods_ext_kpi_info.STANDARD
     *
     * @mbggenerated
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.PURPOSES
     *
     * @return the value of ods_ext_kpi_info.PURPOSES
     *
     * @mbggenerated
     */
    public String getPurposes() {
        return purposes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.PURPOSES
     *
     * @param purposes the value for ods_ext_kpi_info.PURPOSES
     *
     * @mbggenerated
     */
    public void setPurposes(String purposes) {
        this.purposes = purposes == null ? null : purposes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.WEIGHTS
     *
     * @return the value of ods_ext_kpi_info.WEIGHTS
     *
     * @mbggenerated
     */
    public String getWeights() {
        return weights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.WEIGHTS
     *
     * @param weights the value for ods_ext_kpi_info.WEIGHTS
     *
     * @mbggenerated
     */
    public void setWeights(String weights) {
        this.weights = weights == null ? null : weights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_DEF
     *
     * @return the value of ods_ext_kpi_info.KPI_DEF
     *
     * @mbggenerated
     */
    public String getKpiDef() {
        return kpiDef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_DEF
     *
     * @param kpiDef the value for ods_ext_kpi_info.KPI_DEF
     *
     * @mbggenerated
     */
    public void setKpiDef(String kpiDef) {
        this.kpiDef = kpiDef == null ? null : kpiDef.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_kpi_info.KPI_MEMO
     *
     * @return the value of ods_ext_kpi_info.KPI_MEMO
     *
     * @mbggenerated
     */
    public String getKpiMemo() {
        return kpiMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_kpi_info.KPI_MEMO
     *
     * @param kpiMemo the value for ods_ext_kpi_info.KPI_MEMO
     *
     * @mbggenerated
     */
    public void setKpiMemo(String kpiMemo) {
        this.kpiMemo = kpiMemo == null ? null : kpiMemo.trim();
    }
}