package com.infosmart.po;

public class OdsExtAreaSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.LOTID
     *
     * @mbggenerated
     */
    private String lotid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.KPI_NUM
     *
     * @mbggenerated
     */
    private String kpiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.KPI_DEP
     *
     * @mbggenerated
     */
    private String kpiDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.KPI_YM
     *
     * @mbggenerated
     */
    private String kpiYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.KPI_CODE
     *
     * @mbggenerated
     */
    private String kpiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.CLASS_1
     *
     * @mbggenerated
     */
    private String class1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.MONTH_SALES
     *
     * @mbggenerated
     */
    private String monthSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.YEAR_SALES_ACCU
     *
     * @mbggenerated
     */
    private String yearSalesAccu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_area_sales.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.LOTID
     *
     * @return the value of ods_ext_area_sales.LOTID
     *
     * @mbggenerated
     */
    public String getLotid() {
        return lotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.LOTID
     *
     * @param lotid the value for ods_ext_area_sales.LOTID
     *
     * @mbggenerated
     */
    public void setLotid(String lotid) {
        this.lotid = lotid == null ? null : lotid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.KPI_NUM
     *
     * @return the value of ods_ext_area_sales.KPI_NUM
     *
     * @mbggenerated
     */
    public String getKpiNum() {
        return kpiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.KPI_NUM
     *
     * @param kpiNum the value for ods_ext_area_sales.KPI_NUM
     *
     * @mbggenerated
     */
    public void setKpiNum(String kpiNum) {
        this.kpiNum = kpiNum == null ? null : kpiNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.KPI_DEP
     *
     * @return the value of ods_ext_area_sales.KPI_DEP
     *
     * @mbggenerated
     */
    public String getKpiDep() {
        return kpiDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.KPI_DEP
     *
     * @param kpiDep the value for ods_ext_area_sales.KPI_DEP
     *
     * @mbggenerated
     */
    public void setKpiDep(String kpiDep) {
        this.kpiDep = kpiDep == null ? null : kpiDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.KPI_YM
     *
     * @return the value of ods_ext_area_sales.KPI_YM
     *
     * @mbggenerated
     */
    public String getKpiYm() {
        return kpiYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.KPI_YM
     *
     * @param kpiYm the value for ods_ext_area_sales.KPI_YM
     *
     * @mbggenerated
     */
    public void setKpiYm(String kpiYm) {
        this.kpiYm = kpiYm == null ? null : kpiYm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.KPI_CODE
     *
     * @return the value of ods_ext_area_sales.KPI_CODE
     *
     * @mbggenerated
     */
    public String getKpiCode() {
        return kpiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.KPI_CODE
     *
     * @param kpiCode the value for ods_ext_area_sales.KPI_CODE
     *
     * @mbggenerated
     */
    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode == null ? null : kpiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.CLASS_1
     *
     * @return the value of ods_ext_area_sales.CLASS_1
     *
     * @mbggenerated
     */
    public String getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.CLASS_1
     *
     * @param class1 the value for ods_ext_area_sales.CLASS_1
     *
     * @mbggenerated
     */
    public void setClass1(String class1) {
        this.class1 = class1 == null ? null : class1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.MONTH_SALES
     *
     * @return the value of ods_ext_area_sales.MONTH_SALES
     *
     * @mbggenerated
     */
    public String getMonthSales() {
        return monthSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.MONTH_SALES
     *
     * @param monthSales the value for ods_ext_area_sales.MONTH_SALES
     *
     * @mbggenerated
     */
    public void setMonthSales(String monthSales) {
        this.monthSales = monthSales == null ? null : monthSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.YEAR_SALES_ACCU
     *
     * @return the value of ods_ext_area_sales.YEAR_SALES_ACCU
     *
     * @mbggenerated
     */
    public String getYearSalesAccu() {
        return yearSalesAccu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.YEAR_SALES_ACCU
     *
     * @param yearSalesAccu the value for ods_ext_area_sales.YEAR_SALES_ACCU
     *
     * @mbggenerated
     */
    public void setYearSalesAccu(String yearSalesAccu) {
        this.yearSalesAccu = yearSalesAccu == null ? null : yearSalesAccu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_area_sales.UNIT
     *
     * @return the value of ods_ext_area_sales.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_area_sales.UNIT
     *
     * @param unit the value for ods_ext_area_sales.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}