package com.infosmart.po;

public class OdsExtLotSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.LOTID
     *
     * @mbggenerated
     */
    private String lotid;
    private String lotName;

    public String getLotName() {
		return lotName;
	}

	public void setLotName(String lotName) {
		this.lotName = lotName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.KPI_NUM
     *
     * @mbggenerated
     */
    private String kpiNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.KPI_DEP
     *
     * @mbggenerated
     */
    private String kpiDep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.KPI_YM
     *
     * @mbggenerated
     */
    private String kpiYm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.KPI_CODE
     *
     * @mbggenerated
     */
    private String kpiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.CLASS_1
     *
     * @mbggenerated
     */
    private String class1;
    private String class2;
    private String class3;

    public String getClass2() {
		return class2;
	}

	public void setClass2(String class2) {
		this.class2 = class2;
	}

	public String getClass3() {
		return class3;
	}

	public void setClass3(String class3) {
		this.class3 = class3;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.SALES
     *
     * @mbggenerated
     */
    private String sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ods_ext_lot_sales.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.LOTID
     *
     * @return the value of ods_ext_lot_sales.LOTID
     *
     * @mbggenerated
     */
    public String getLotid() {
        return lotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.LOTID
     *
     * @param lotid the value for ods_ext_lot_sales.LOTID
     *
     * @mbggenerated
     */
    public void setLotid(String lotid) {
        this.lotid = lotid == null ? null : lotid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.KPI_NUM
     *
     * @return the value of ods_ext_lot_sales.KPI_NUM
     *
     * @mbggenerated
     */
    public String getKpiNum() {
        return kpiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.KPI_NUM
     *
     * @param kpiNum the value for ods_ext_lot_sales.KPI_NUM
     *
     * @mbggenerated
     */
    public void setKpiNum(String kpiNum) {
        this.kpiNum = kpiNum == null ? null : kpiNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.KPI_DEP
     *
     * @return the value of ods_ext_lot_sales.KPI_DEP
     *
     * @mbggenerated
     */
    public String getKpiDep() {
        return kpiDep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.KPI_DEP
     *
     * @param kpiDep the value for ods_ext_lot_sales.KPI_DEP
     *
     * @mbggenerated
     */
    public void setKpiDep(String kpiDep) {
        this.kpiDep = kpiDep == null ? null : kpiDep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.KPI_YM
     *
     * @return the value of ods_ext_lot_sales.KPI_YM
     *
     * @mbggenerated
     */
    public String getKpiYm() {
        return kpiYm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.KPI_YM
     *
     * @param kpiYm the value for ods_ext_lot_sales.KPI_YM
     *
     * @mbggenerated
     */
    public void setKpiYm(String kpiYm) {
        this.kpiYm = kpiYm == null ? null : kpiYm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.KPI_CODE
     *
     * @return the value of ods_ext_lot_sales.KPI_CODE
     *
     * @mbggenerated
     */
    public String getKpiCode() {
        return kpiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.KPI_CODE
     *
     * @param kpiCode the value for ods_ext_lot_sales.KPI_CODE
     *
     * @mbggenerated
     */
    public void setKpiCode(String kpiCode) {
        this.kpiCode = kpiCode == null ? null : kpiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.CLASS_1
     *
     * @return the value of ods_ext_lot_sales.CLASS_1
     *
     * @mbggenerated
     */
    public String getClass1() {
        return class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.CLASS_1
     *
     * @param class1 the value for ods_ext_lot_sales.CLASS_1
     *
     * @mbggenerated
     */
    public void setClass1(String class1) {
        this.class1 = class1 == null ? null : class1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.SALES
     *
     * @return the value of ods_ext_lot_sales.SALES
     *
     * @mbggenerated
     */
    public String getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.SALES
     *
     * @param sales the value for ods_ext_lot_sales.SALES
     *
     * @mbggenerated
     */
    public void setSales(String sales) {
        this.sales = sales == null ? null : sales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ods_ext_lot_sales.UNIT
     *
     * @return the value of ods_ext_lot_sales.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ods_ext_lot_sales.UNIT
     *
     * @param unit the value for ods_ext_lot_sales.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}