package com.infosmart.po;

/*
 * Alipay.com Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
// auto generated imports
import java.util.Date;
import java.math.BigDecimal;

/**
 * A data object class directly models database table <tt>DWPAS_C_PRD_DIM</tt>.
 *
 * This file is generated by <tt>paygw-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>paygw</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/dwpas_c_prd_dim.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>paygw-dalgen</tt> 
 * to generate this file.
 *
 * @author Cheng Li
 */
public class PrdDimInfo {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>PRODUCT_ID</tt>.
	 */
	private String productId;

	/**
	 * This property corresponds to db column <tt>DIM1_CODE</tt>.
	 */
	private String dim1Code;

	/**
	 * This property corresponds to db column <tt>DIM1_IN_VALUE</tt>.
	 */
	private BigDecimal dim1InValue;

	/**
	 * This property corresponds to db column <tt>DIM1_OUT_VALUE</tt>.
	 */
	private BigDecimal dim1OutValue;

	/**
	 * This property corresponds to db column <tt>DIM2_CODE</tt>.
	 */
	private String dim2Code;

	/**
	 * This property corresponds to db column <tt>DIM2_IN_VALUE</tt>.
	 */
	private BigDecimal dim2InValue;

	/**
	 * This property corresponds to db column <tt>DIM2_OUT_VALUE</tt>.
	 */
	private BigDecimal dim2OutValue;

	/**
	 * This property corresponds to db column <tt>DIM3_CODE</tt>.
	 */
	private String dim3Code;

	/**
	 * This property corresponds to db column <tt>DIM3_IN_VALUE</tt>.
	 */
	private BigDecimal dim3InValue;

	/**
	 * This property corresponds to db column <tt>DIM3_OUT_VALUE</tt>.
	 */
	private BigDecimal dim3OutValue;

	/**
	 * This property corresponds to db column <tt>DIM4_CODE</tt>.
	 */
	private String dim4Code;

	/**
	 * This property corresponds to db column <tt>DIM4_IN_VALUE</tt>.
	 */
	private BigDecimal dim4InValue;

	/**
	 * This property corresponds to db column <tt>DIM4_OUT_VALUE</tt>.
	 */
	private BigDecimal dim4OutValue;

	/**
	 * This property corresponds to db column <tt>DIM5_CODE</tt>.
	 */
	private String dim5Code;

	/**
	 * This property corresponds to db column <tt>DIM5_IN_VALUE</tt>.
	 */
	private BigDecimal dim5InValue;

	/**
	 * This property corresponds to db column <tt>DIM5_OUT_VALUE</tt>.
	 */
	private BigDecimal dim5OutValue;

	/**
	 * This property corresponds to db column <tt>DIM6_CODE</tt>.
	 */
	private String dim6Code;

	/**
	 * This property corresponds to db column <tt>DIM6_IN_VALUE</tt>.
	 */
	private BigDecimal dim6InValue;

	/**
	 * This property corresponds to db column <tt>DIM6_OUT_VALUE</tt>.
	 */
	private BigDecimal dim6OutValue;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;
	private String operFlag;

	private String keyWord;
	
	private String productName;
	private String dim1Name;
	private String dim2Name;
	private String dim3Name;
	private String dim4Name;
	private String dim5Name;
	private String dim6Name;
	private String dim1Url;
	private String dim2Url;
	private String dim3Url;
	private String dim4Url;
	private String dim5Url;
	private String dim6Url;

    //========== getters and setters ==========
	
	public String getOperFlag() {
		return operFlag;
	}

	public String getDim1Url() {
		return dim1Url;
	}

	public void setDim1Url(String dim1Url) {
		this.dim1Url = dim1Url;
	}

	public String getDim2Url() {
		return dim2Url;
	}

	public void setDim2Url(String dim2Url) {
		this.dim2Url = dim2Url;
	}

	public String getDim3Url() {
		return dim3Url;
	}

	public void setDim3Url(String dim3Url) {
		this.dim3Url = dim3Url;
	}

	public String getDim4Url() {
		return dim4Url;
	}

	public void setDim4Url(String dim4Url) {
		this.dim4Url = dim4Url;
	}

	public String getDim5Url() {
		return dim5Url;
	}

	public void setDim5Url(String dim5Url) {
		this.dim5Url = dim5Url;
	}

	public String getDim6Url() {
		return dim6Url;
	}

	public void setDim6Url(String dim6Url) {
		this.dim6Url = dim6Url;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	

	public String getDim1Name() {
		return dim1Name;
	}

	public void setDim1Name(String dim1Name) {
		this.dim1Name = dim1Name;
	}

	public String getDim2Name() {
		return dim2Name;
	}

	public void setDim2Name(String dim2Name) {
		this.dim2Name = dim2Name;
	}

	public String getDim3Name() {
		return dim3Name;
	}

	public void setDim3Name(String dim3Name) {
		this.dim3Name = dim3Name;
	}

	public String getDim4Name() {
		return dim4Name;
	}

	public void setDim4Name(String dim4Name) {
		this.dim4Name = dim4Name;
	}

	public String getDim5Name() {
		return dim5Name;
	}

	public void setDim5Name(String dim5Name) {
		this.dim5Name = dim5Name;
	}

	public String getDim6Name() {
		return dim6Name;
	}

	public void setDim6Name(String dim6Name) {
		this.dim6Name = dim6Name;
	}

	public void setOperFlag(String operFlag) {
		this.operFlag = operFlag;
	}

	public String getKeyWord() {
		return keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	/**
     * Getter method for property <tt>productId</tt>.
     *
     * @return property value of productId
     */
	public String getProductId() {
		return productId;
	}
	
	/**
	 * Setter method for property <tt>productId</tt>.
	 * 
	 * @param productId value to be assigned to property productId
     */
	public void setProductId(String productId) {
		this.productId = productId;
	}

    /**
     * Getter method for property <tt>dim1Code</tt>.
     *
     * @return property value of dim1Code
     */
	public String getDim1Code() {
		return dim1Code;
	}
	
	/**
	 * Setter method for property <tt>dim1Code</tt>.
	 * 
	 * @param dim1Code value to be assigned to property dim1Code
     */
	public void setDim1Code(String dim1Code) {
		this.dim1Code = dim1Code;
	}

    /**
     * Getter method for property <tt>dim1InValue</tt>.
     *
     * @return property value of dim1InValue
     */
	public BigDecimal getDim1InValue() {
		return dim1InValue;
	}
	
	/**
	 * Setter method for property <tt>dim1InValue</tt>.
	 * 
	 * @param dim1InValue value to be assigned to property dim1InValue
     */
	public void setDim1InValue(BigDecimal dim1InValue) {
		this.dim1InValue = dim1InValue;
	}

    /**
     * Getter method for property <tt>dim1OutValue</tt>.
     *
     * @return property value of dim1OutValue
     */
	public BigDecimal getDim1OutValue() {
		return dim1OutValue;
	}
	
	/**
	 * Setter method for property <tt>dim1OutValue</tt>.
	 * 
	 * @param dim1OutValue value to be assigned to property dim1OutValue
     */
	public void setDim1OutValue(BigDecimal dim1OutValue) {
		this.dim1OutValue = dim1OutValue;
	}

    /**
     * Getter method for property <tt>dim2Code</tt>.
     *
     * @return property value of dim2Code
     */
	public String getDim2Code() {
		return dim2Code;
	}
	
	/**
	 * Setter method for property <tt>dim2Code</tt>.
	 * 
	 * @param dim2Code value to be assigned to property dim2Code
     */
	public void setDim2Code(String dim2Code) {
		this.dim2Code = dim2Code;
	}

    /**
     * Getter method for property <tt>dim2InValue</tt>.
     *
     * @return property value of dim2InValue
     */
	public BigDecimal getDim2InValue() {
		return dim2InValue;
	}
	
	/**
	 * Setter method for property <tt>dim2InValue</tt>.
	 * 
	 * @param dim2InValue value to be assigned to property dim2InValue
     */
	public void setDim2InValue(BigDecimal dim2InValue) {
		this.dim2InValue = dim2InValue;
	}

    /**
     * Getter method for property <tt>dim2OutValue</tt>.
     *
     * @return property value of dim2OutValue
     */
	public BigDecimal getDim2OutValue() {
		return dim2OutValue;
	}
	
	/**
	 * Setter method for property <tt>dim2OutValue</tt>.
	 * 
	 * @param dim2OutValue value to be assigned to property dim2OutValue
     */
	public void setDim2OutValue(BigDecimal dim2OutValue) {
		this.dim2OutValue = dim2OutValue;
	}

    /**
     * Getter method for property <tt>dim3Code</tt>.
     *
     * @return property value of dim3Code
     */
	public String getDim3Code() {
		return dim3Code;
	}
	
	/**
	 * Setter method for property <tt>dim3Code</tt>.
	 * 
	 * @param dim3Code value to be assigned to property dim3Code
     */
	public void setDim3Code(String dim3Code) {
		this.dim3Code = dim3Code;
	}

    /**
     * Getter method for property <tt>dim3InValue</tt>.
     *
     * @return property value of dim3InValue
     */
	public BigDecimal getDim3InValue() {
		return dim3InValue;
	}
	
	/**
	 * Setter method for property <tt>dim3InValue</tt>.
	 * 
	 * @param dim3InValue value to be assigned to property dim3InValue
     */
	public void setDim3InValue(BigDecimal dim3InValue) {
		this.dim3InValue = dim3InValue;
	}

    /**
     * Getter method for property <tt>dim3OutValue</tt>.
     *
     * @return property value of dim3OutValue
     */
	public BigDecimal getDim3OutValue() {
		return dim3OutValue;
	}
	
	/**
	 * Setter method for property <tt>dim3OutValue</tt>.
	 * 
	 * @param dim3OutValue value to be assigned to property dim3OutValue
     */
	public void setDim3OutValue(BigDecimal dim3OutValue) {
		this.dim3OutValue = dim3OutValue;
	}

    /**
     * Getter method for property <tt>dim4Code</tt>.
     *
     * @return property value of dim4Code
     */
	public String getDim4Code() {
		return dim4Code;
	}
	
	/**
	 * Setter method for property <tt>dim4Code</tt>.
	 * 
	 * @param dim4Code value to be assigned to property dim4Code
     */
	public void setDim4Code(String dim4Code) {
		this.dim4Code = dim4Code;
	}

    /**
     * Getter method for property <tt>dim4InValue</tt>.
     *
     * @return property value of dim4InValue
     */
	public BigDecimal getDim4InValue() {
		return dim4InValue;
	}
	
	/**
	 * Setter method for property <tt>dim4InValue</tt>.
	 * 
	 * @param dim4InValue value to be assigned to property dim4InValue
     */
	public void setDim4InValue(BigDecimal dim4InValue) {
		this.dim4InValue = dim4InValue;
	}

    /**
     * Getter method for property <tt>dim4OutValue</tt>.
     *
     * @return property value of dim4OutValue
     */
	public BigDecimal getDim4OutValue() {
		return dim4OutValue;
	}
	
	/**
	 * Setter method for property <tt>dim4OutValue</tt>.
	 * 
	 * @param dim4OutValue value to be assigned to property dim4OutValue
     */
	public void setDim4OutValue(BigDecimal dim4OutValue) {
		this.dim4OutValue = dim4OutValue;
	}

    /**
     * Getter method for property <tt>dim5Code</tt>.
     *
     * @return property value of dim5Code
     */
	public String getDim5Code() {
		return dim5Code;
	}
	
	/**
	 * Setter method for property <tt>dim5Code</tt>.
	 * 
	 * @param dim5Code value to be assigned to property dim5Code
     */
	public void setDim5Code(String dim5Code) {
		this.dim5Code = dim5Code;
	}

    /**
     * Getter method for property <tt>dim5InValue</tt>.
     *
     * @return property value of dim5InValue
     */
	public BigDecimal getDim5InValue() {
		return dim5InValue;
	}
	
	/**
	 * Setter method for property <tt>dim5InValue</tt>.
	 * 
	 * @param dim5InValue value to be assigned to property dim5InValue
     */
	public void setDim5InValue(BigDecimal dim5InValue) {
		this.dim5InValue = dim5InValue;
	}

    /**
     * Getter method for property <tt>dim5OutValue</tt>.
     *
     * @return property value of dim5OutValue
     */
	public BigDecimal getDim5OutValue() {
		return dim5OutValue;
	}
	
	/**
	 * Setter method for property <tt>dim5OutValue</tt>.
	 * 
	 * @param dim5OutValue value to be assigned to property dim5OutValue
     */
	public void setDim5OutValue(BigDecimal dim5OutValue) {
		this.dim5OutValue = dim5OutValue;
	}

    /**
     * Getter method for property <tt>dim6Code</tt>.
     *
     * @return property value of dim6Code
     */
	public String getDim6Code() {
		return dim6Code;
	}
	
	/**
	 * Setter method for property <tt>dim6Code</tt>.
	 * 
	 * @param dim6Code value to be assigned to property dim6Code
     */
	public void setDim6Code(String dim6Code) {
		this.dim6Code = dim6Code;
	}

    /**
     * Getter method for property <tt>dim6InValue</tt>.
     *
     * @return property value of dim6InValue
     */
	public BigDecimal getDim6InValue() {
		return dim6InValue;
	}
	
	/**
	 * Setter method for property <tt>dim6InValue</tt>.
	 * 
	 * @param dim6InValue value to be assigned to property dim6InValue
     */
	public void setDim6InValue(BigDecimal dim6InValue) {
		this.dim6InValue = dim6InValue;
	}

    /**
     * Getter method for property <tt>dim6OutValue</tt>.
     *
     * @return property value of dim6OutValue
     */
	public BigDecimal getDim6OutValue() {
		return dim6OutValue;
	}
	
	/**
	 * Setter method for property <tt>dim6OutValue</tt>.
	 * 
	 * @param dim6OutValue value to be assigned to property dim6OutValue
     */
	public void setDim6OutValue(BigDecimal dim6OutValue) {
		this.dim6OutValue = dim6OutValue;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
